### ISSUE TITLE
Provide distinct codes and help links for warnings and messages

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#131]
Whenever we log warnings or errors we should have a distinct code, and ideally a help url (backed by an aka.ms link)
pointing to specific help documentation. For example, errors about ContainerPort formatting might point to the docs we have about ContainerPort specifically.

As part of this work we should make the repo localizable (not necessarily localized) - messages should be extracted out to Rexs resources so that we're prepared for onelocbuild onboarding.

**Comment by vlada-shubina** [comment]
Related:
https://github.com/dotnet/sdk-container-builds/issues/317
https://github.com/dotnet/sdk-container-builds/issues/278
https://github.com/dotnet/sdk-container-builds/issues/100

**Comment by MichalPavlik** [comment]
Subtasks:
- [ ] #328
- [ ] TODO

**Comment by vlada-shubina** [comment]
Sub task: https://github.com/dotnet/sdk-container-builds/issues/365

**Comment by vlada-shubina** [comment]
Closing this item as done.
The only item remaining is https://github.com/dotnet/sdk-container-builds/issues/331, it is done from our side, pending investigation why it doesn't work as expected during Publish in VS.
