### ISSUE TITLE
Support building multiple tags at once

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#137]
The tags that are built for an image are often set many times by users - for example a `latest` tag and a Version-specific tag.  We should enable this.

One easy way of doing this would be to interpret the `ContainerImageTag` property as a semicolon-delimited list of desired tags, iterating over that list when the final built images are pushed.

**Comment by frivard-coveo** [comment]
I suggest going with the `TargetFrameworks` approach:
- either the user has only `ContainerImageTag` defined, and this is a single tag (no semicolon)
- or the user has only `ContainerImageTags` defined, and this represent a list of semi-colon separated tags.

This would be familiar with those who work with multi-targeting (example `<TargetFrameworks>netframework4.8;net6.0</TargetFrameworks>`).
