### ISSUE TITLE
Move Microsoft.NET.Build.Containers to SDK

### ISSUE THREAD

**Issue by alrz** [dotnet/sdk-container-builds#139]
Would be nice if dotnet publish supports image build as a built-in functionality.

**Comment by baronfel** [comment]
I agree, and this is already our plan! The container building functionality will ship from this repo while we are iterating quickly, but once we fill out the feature set we will incorporate it into the SDK directly.

**Comment by Rick-Anderson** [comment]
```
# create a new project and move to its directory
dotnet new mvc -n my-awesome-container-app
cd my-awesome-container-app

# add a reference to a (temporary) package that creates the container
dotnet add package Microsoft.NET.Build.Containers
```

That explains the `temporary` in [Announcing built-in container support for the .NET SDK](https://devblogs.microsoft.com/dotnet/announcing-builtin-container-support-for-the-dotnet-sdk/)

**Comment by baronfel** [comment]
For the 7.0.200 SDK release, web projects will get this included as an implicit PackageReference. For the 7.0.300 series of SDKs we're targeting full inclusion for all project types.

**Comment by vlada-shubina** [comment]
Subtasks:
- https://github.com/dotnet/sdk-container-builds/issues/339
- https://github.com/dotnet/sdk-container-builds/issues/340
