### ISSUE TITLE
Add ability to specify the ContainerImageName in the publish step

### ISSUE THREAD

**Issue by MarkStega** [dotnet/sdk-container-builds#147]
I would like to specify the container image name on the publish command line or a publish profile.

The issue with specifying it in the csproj is that I have a preview image name (like icebg.web.ds.wip:2022-08-26--18-56-08--WIP) and a different name for releases (like icebg.web.ds:2022-08-02--14-36-17--1.0.0-preview.2). This allows me to have clearly labeled test and production versions in separate repositories in my ACR.

This whole 'publish do a container' is a great feature.

**Comment by baronfel** [comment]
@MarkStega Can you use `-p:ContainerImageName=<whatever you want here>`? There are docs/examples of this [here](https://github.com/dotnet/sdk-container-builds/blob/main/docs/ContainerCustomization.md#containerimagename), and it should allow you to override the defaults we provide.

**Comment by MarkStega** [comment]
I can and it works!  I didn't know that any property could be over ridden in that fashion. So I knew about the ContainerImageName property but not the ability to set it outside of the csproj.
