### ISSUE TITLE
Misc. permissions issues when running on the Chiseled images

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#148]
Use the following customizations to a web project:

```xml
    <ContainerBaseImage>mcr.microsoft.com/dotnet/nightly/aspnet:6.0-jammy-chiseled</ContainerBaseImage>
```

Publish and run the project and you'll see the following permissions error:

```
exec /app/sdk-container-demo: permission denied
```

I can't get a shell in this image (on purpose) so instead I started looking at permissions on the layer we generate on a non-chiseled image:

```terminal
# ls -la
total 296
drwxr-xr-x 3 root root   4096 Aug 17 20:16 .
drwxr-xr-x 1 root root   4096 Aug 27 17:16 ..
-rw-r--r-- 1 1001  121    119 Aug 17 19:21 appsettings.Development.json
-rw-r--r-- 1 1001  121    142 Aug 17 19:21 appsettings.json
-rw-r--r-- 1 1001  121     61 Aug 17 19:21 global.json
-rw-r--r-- 1 1001  121    578 Aug 17 19:21 nuget.config
-rwxr-xr-x 1 1001  121 181016 Aug 17 19:21 sdk-container-demo
-rw-r--r-- 1 1001  121    963 Aug 17 19:21 sdk-container-demo.deps.json
-rw-r--r-- 1 1001  121  43008 Aug 17 19:21 sdk-container-demo.dll
-rw-r--r-- 1 1001  121  33524 Aug 17 19:21 sdk-container-demo.pdb
-rw-r--r-- 1 1001  121    505 Aug 17 19:21 sdk-container-demo.runtimeconfig.json
drwxr-xr-x 5 root root   4096 Aug 17 20:16 wwwroot
```

Interesting - the `wwwroot`, `app`, and current directory are owned by `root:root` instead of the user/group of the app itself. This possibly means we need to take user/group into account when creating the layer?

Separately the chiseled images set `ASPNETCORE_URLS` to bind to port `8080` instead, so if we want to keep our current helper around automatically setting image metadata we will likely need additional checks here.  The safest thing might be to move away from directly setting Port information in the targets and instead move that into the ParseContainerProperties task (or another explicit Task). We'd need to determine and retrieve the base image config and read the environment variables to check if ASPNETCORE_URLS is provided, and if so parse the expression and try to get the relevant port numbers out of it, returning `ContainerPort` `ITaskItem[]` of the discovered ports.

**Comment by baronfel** [comment]
The ownership issues seem to be because we do not explicitly create Tar entries for the directories that may be included in the app. As a result these seem to be made with root:root permissions.  I hacked up the codebase a ton to

* support get/set of User in the image configuration,
* flow user through to the Layer creation logic,
* changed layer file creation to walk the directory tree for the destination paths and ensure that explicit directory TarEntries were added with the User field set to the user on the image (note that this _may not exist_ for many images, including Microsoft images!)
* then changed the existing end-to-end integration test to use the chiseled images and pass-through the User encoded in those images (which happens to be `app`).

After I did this, the Hello World application ran! This leads me to believe that we need to move to explicit entry creation soon.

**Comment by baronfel** [comment]
I've strangely been unable to replicate this. [baronfel/sdk-container-demo](https://github.com/baronfel/sdk-container-demo/actions/runs/3768156793/jobs/6406352025) has an run in GitHub Actions where we can build a chiseled container just fine, and this container runs well locally in my testing. Maybe my test scenario here was messed up?

**Comment by baronfel** [comment]
I think our only action here should be to bring a test similar to this linked action into this repo to check against regressions, then close this issue.

**Comment by laurentkempe** [comment]
I am trying to deploy an ubuntu chiseled images of a Minimal API empty template on 
Azure Container App.
Using `mcr.microsoft.com/dotnet/nightly/runtime-deps:7.0-jammy-chiseled` I am getting the error "Unhandled exception. [http://System.Net](https://t.co/9HeQBEWV0E).Sockets.SocketException (13): Permission denied" on Azure Container App.

When I change base image to `mcr.microsoft.com/dotnet/runtime:7.0` it works!

I guess the permission you mention is the main issue.

**Comment by baronfel** [comment]
Can you check what ports and environment variables your built image is looking for? 'docker inspect IMAGENAME@TAG' should provide all of that information

**Comment by laurentkempe** [comment]
@baronfel I have found the problem, and it is related to the port which is per default with the SDK the port 80. So, with chiseled based image the problem is that it is rootless and cannot expose port below 1024.

I changed with following settings, and it should work with that

```xml
  <PropertyGroup> <!-- Docker continer configuration-->
    <ContainerImageName>nuke-pulumi-aca-dotnet-webapi</ContainerImageName>
    <ContainerBaseImage>mcr.microsoft.com/dotnet/nightly/runtime-deps:7.0-jammy-chiseled</ContainerBaseImage>
    <PublishTrimmed>true</PublishTrimmed>
    <SelfContained>true</SelfContained>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ContainerPort Include="5000" Type="tcp" />
    <ContainerEnvironmentVariable Include="ASPNETCORE_URLS" Value="http://+:5000" />
  </ItemGroup>
```

**Comment by baronfel** [comment]
ah, perfect. So I think in the end this issue is the same as https://github.com/dotnet/sdk-container-builds/issues/165. One thing I noticed is that our custom setting of Port/ASPNETCORE_URLS may not have any value at all - those are present in the underlying container image for aspnet already: https://github.com/dotnet/dotnet-docker/blob/main/src/runtime-deps/6.0/jammy/amd64/Dockerfile#L19.

So is there any value for us inferring Port/ASPNETCORE_URLS at all? I say no, and therefore we should probably just remove it.

**Comment by baronfel** [comment]
Yeah, I checked that `mcr.microsoft.com/dotnet/nightly/runtime-deps:7.0-jammy-chiseled` has an ASPNETCORE_URLS variable set to `http://+8080`, and that would Just Work if we didn't do anything special in the targets. We should be clear to just remove this customization entirely.

**Comment by baronfel** [comment]
@laurentkempe want to try with version 0.3.0-alpha.18 from GitHub packages and see if that works without overrides for you? I'd expect the URL to be 8080 without customizations.

**Comment by laurentkempe** [comment]
@baronfel I don't have access rights to get the package

**Comment by baronfel** [comment]
@laurentkempe were you using our instructions in the [DEVGUIDE](https://github.com/dotnet/sdk-container-builds/blob/main/DEVGUIDE.md)? 
Anyone should be able to read the packages, you just have to set up a GitHub key in your nuget config to authenticate.

**Comment by laurentkempe** [comment]
@baronfel I didn't realized that there was a DEVGUIDE, never mind, I cloned and built locally.

> I'd expect the URL to be 8080 without customizations.

It works 🎉🎉🎉 and now it works on Azure Container App 👍🏼
