### ISSUE TITLE
CreateNewImageToolTask should use CommandLineBuilder

### ISSUE THREAD

**Issue by BenVillalobos** [dotnet/sdk-container-builds#172]
For later refactor: this should use `Microsoft.Build.Utilities.CommandLineBuilder` (and @baronfel, we should probably expend some effort to make sure `CommandLineBuilder` plays well with S.CL).

_Originally posted by @rainersigwald in https://github.com/dotnet/sdk-container-builds/pull/164#discussion_r974317890_

**Comment by vlada-shubina** [comment]
Working on this in https://github.com/dotnet/sdk-container-builds/pull/349, will try to target this too.

**Comment by baronfel** [comment]
Done in #349
