### ISSUE TITLE
Login to private registry

### ISSUE THREAD

**Issue by itcozum** [dotnet/sdk-container-builds#182]
Hi,
How can I login to my private docker registry?

**Comment by baronfel** [comment]
You cannot currently. Auth support is very important and something that the team is currently working on implementing.

**Comment by itcozum** [comment]
how soon should we be expecting an upgrade with regard to this issue?

**Comment by baronfel** [comment]
We aim to have this completed by the .NET 7 release in November, but in the meantime you can follow [this issue](https://github.com/dotnet/sdk-container-builds/issues/70) and any PRs linked to it for more up-to-date status. When it merges, you can use it immediately via the github package feed for this repository as described [here](https://github.com/dotnet/sdk-container-builds/blob/main/DEVGUIDE.md#using-the-prerelease-package-from-this-repository), or you can wait a bit longer while we work on an announcement post + official release.

**Comment by caner-gurelsoy** [comment]
hi,
any good news abt this subject?

**Comment by baronfel** [comment]
Yes!  As of the 0.2.7 release of this package (this week) we support private registry authentication! See [the in-repo docs](https://github.com/dotnet/sdk-container-builds/blob/main/docs/RegistryAuthentication.md) for details, but in general if you can authenticate via docker login to your registry (or use a credential helper to manage that authentication), then we will respect that configuration.
