### ISSUE TITLE
Task object support for credentials

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/sdk-container-builds#186]
In VS scenarios when there is no local Docker, `docker-credential-desktop` will not exist. We can still query plaintext credentials from the JSON file in `~`, but that's not ideal.

For other publish scenarios, Visual Studio can store credentials in its own way, and pass them to MSBuild tasks via host objects. We should support that for our task too.

**Comment by baronfel** [comment]
On top of this, we'll need to teach the `containerize` app how to read the credentials from stdin so that VS can pass the credentials along without them ending up in environment variables or MSBuild logs.
