### ISSUE TITLE
No image is created on Fedora

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk-container-builds#222]
I'm following the steps in the [blog post](https://devblogs.microsoft.com/dotnet/announcing-builtin-container-support-for-the-dotnet-sdk/) with .NET 6.0.108 sdk on Fedora 36.

Fedora comes with `podman` instead of `docker`.
I have the package installed that provides a `docker` executable that calls `podman` under the hood.

```
dotnet new mvc -n my-awesome-container-app
cd my-awesome-container-app

# add a reference to a (temporary) package that creates the container
dotnet add package Microsoft.NET.Build.Containers

# publish your project for linux-x64
dotnet publish --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer
```

This last step outputs:
```
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /tmp/my-awesome-container-app/my-awesome-container-app.csproj (in 418 ms).
  my-awesome-container-app -> /tmp/my-awesome-container-app/bin/Release/net6.0/linux-x64/my-awesome-container-app.dll
  my-awesome-container-app -> /tmp/my-awesome-container-app/bin/Release/net6.0/linux-x64/publish/
```
The exit code is `0` (success), but no images were produced:
```
$ podman images
REPOSITORY  TAG         IMAGE ID    CREATED     SIZE
```

@rainersigwald @baronfel any thoughts why I don't get an image?

It would be good to have some error/warning and a non-zero exit code when no image is created.

cc @omajid

**Comment by baronfel** [comment]
Your SDK version is too low to activate the feature - you need at least 7.0.100-preview.7 in order to work. The next version of this package (coming very soon) detects SDK versions and gives build errors if you're using an incompatible SDK.

**Comment by tmds** [comment]
> Your SDK version is too low to activate the feature - you need at least 7.0.100-preview.7 in order to work. The next version of this package (coming very soon) detects SDK versions and gives build errors if you're using an incompatible SDK.

Ah, I missed that.

With 7.0-rc2, I'm up and running:
```
  Pushed container 'my-awesome-container-app:1.0.0' to registry 'docker://'
```
Thanks!

> The next version of this package (coming very soon) detects SDK versions and gives build errors if you're using an incompatible SDK.

:+1:

**Comment by baronfel** [comment]
Glad to hear it! If you want to play with the new bits, every merge to main pushes new packages to Github's nuget feed. There are instructions on how to configure the nuget package source here: https://github.com/dotnet/sdk-container-builds/blob/main/DEVGUIDE.md
