### ISSUE TITLE
Re-introduce caching of authentication methods

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#224]
We should cache retrieved authentication data for registry interactions.

The cache should be
* concurrent
* keyed by host, authentication scheme (Bearer or Basic), 'service', and 'scopes'

This will ensure the correct amount of uniqueness.

**Comment by rainersigwald** [comment]
From what I saw in a typical invocation we're likely to use many of the same scopes or have like a "superset" concept--do we need to be smart enough that scope `name:push,pull` is returned when we request `pull`? Do we even have a way to know the needed scope before making a request, or do we need to check the cache, make a request, get a 401, check the cache again, and if not there, try to get a token?

**Comment by baronfel** [comment]
I'm not sure we can actively parse and handle the scopes. Based on [these docs](https://docs.docker.com/registry/spec/auth/scope/) the scopes have a given structure but no consistent semantics across registries.

**Comment by rainersigwald** [comment]
#235 should be enough for this, though I took a different approach than mentioned above and cached by "url except query string".
