### ISSUE TITLE
Provide the image digest as a MSBuild value

### ISSUE THREAD

**Issue by stan-sz** [dotnet/sdk-container-builds#243]
Upon pushing an image to a registry, can the image digest be exposed to MSBuild in form of a property or an item?

**Comment by rainersigwald** [comment]
Yes, I think that's a good idea. We should return the canonical digest returned by the registry, rather than the one we pushed (in case the registry normalizes JSON), so this will need some work on both the "library" side and the "task" side.

**Comment by baronfel** [comment]
This is great, definitely would take external contributions here. It should be fairly easy to knock out if someone wanted to dip their toes in.

**Comment by baronfel** [comment]
The `GeneratedContainerDigest` property is set with the digest of the created image now - feel free to use it! We also set `GeneratedContainerManifest` to the JSON of the manifest, and `GeneratedContainerConfiguration` with the JSON of the image manifest. Finally, if the container was pushed to a local tarball we provide the `GeneratedArchiveOutputPath` property to point to that location.
