### ISSUE TITLE
RUN equivalent?

### ISSUE THREAD

**Issue by Alumniminium** [dotnet/sdk-container-builds#260]
I am building a container that requires a Font to be installed, in my dockerfile I'd just add a `RUN apk add [font]` line, what's the equivalent in the csproj?

**Comment by Alumniminium** [comment]
Oh, I see now

`Note The only exception to this is RUN commands - due to the way we build containers, those cannot be emulated. If you need this functionality, you will need to use a Dockerfile to build your container images.`

**Comment by rainersigwald** [comment]
That's correct. Another option is to create a custom base image along the lines of:

```Dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:7.0

RUN apk add [font]
```

The downside of this, though, is that you'll have to keep up with servicing releases of the `dotnet` image, which you won't get for free as you do when we infer the base image (or you explicitly specify one of the "evergreen" Microsoft base images).
