### ISSUE TITLE
CLI build error if tags are specified

### ISSUE THREAD

**Issue by Kiryuumaru** [dotnet/sdk-container-builds#262]
CLI build error if tags are specified. I build my app on ubuntu bash github action with this command:
```bash
dotnet publish web.csproj -o output -c Release \
         -r linux-x64 \
         --self-contained \
         -p PublishProfile=DefaultContainer \
         -p ContainerImageName=server_web_ui \
         -p ContainerImageTags=build.422;v0.1.0-alpha.10;latest
```
Error:
```
Building image 'server_web_api' with tags  on top of base image mcr.microsoft.com/dotnet/runtime-deps:7.0
/home/runner/work/_temp/af56fd15-352e-42c1-b635-5e1eb48e7c25.sh: line 60: v0.1.0-alpha.10: command not found
Error: Process completed with exit code 127.
```

**Comment by baronfel** [comment]
Can you create a [bin log](https://aka.ms/binlog) and either take a look at the `PublishContainer` target to see how those values were passed into the `CreateNewImage` task? You could also email it to me at chethusk at microsoft.com if you were unsure how to inspect it.

**Comment by rainersigwald** [comment]
@Kiryuumaru, `;` is a special character in bash, so you'll need to either escape it or quote around it. Can you try this?

```bash
dotnet publish web.csproj -o output -c Release \
         -r linux-x64 \
         --self-contained \
         -p PublishProfile=DefaultContainer \
         -p ContainerImageName=server_web_ui \
         -p "ContainerImageTags=build.422;v0.1.0-alpha.10;latest"

**Comment by Kiryuumaru** [comment]
> @Kiryuumaru, `;` is a special character in bash, so you'll need to either escape it or quote around it. Can you try this?
> 
> ```shell
> dotnet publish web.csproj -o output -c Release \
>          -r linux-x64 \
>          --self-contained \
>          -p PublishProfile=DefaultContainer \
>          -p ContainerImageName=server_web_ui \
>          -p "ContainerImageTags=build.422;v0.1.0-alpha.10;latest"
> ```
Thankyou for the response. I tried that and it gives me a different error:
```
MSBuild version 17.4.0+18d5aef85 for .NET
MSBUILD : error MSB1006: Property is not valid.
Switch: v0.1.0-alpha.10
```

**Comment by Kiryuumaru** [comment]
> Can you create a [bin log](https://aka.ms/binlog) and either take a look at the `PublishContainer` target to see how those values were passed into the `CreateNewImage` task? You could also email it to me at chethusk at microsoft.com if you were unsure how to inspect it.

I tried building it with binlogs (-bl:msbuild.binlog) but the compiler was not able to generate the logs. I think the error throws earlier than the log creation

**Comment by Kiryuumaru** [comment]
> > Thankyou for the response. I tried that and it gives me a different error:
> > ```
> > MSBuild version 17.4.0+18d5aef85 for .NET
> > MSBUILD : error MSB1006: Property is not valid.
> > Switch: v0.1.0-alpha.10
> > ```
> 
> Hmm, try `-p ContainerImageTags="build.422;v0.1.0-alpha.10;latest"` please?

Tried that too, same error:
```
MSBuild version 17.4.0+18d5aef85 for .NET
MSBUILD : error MSB1006: Property is not valid.
Switch: v0.1.0-alpha.10
```

**Comment by peter-dolkens** [comment]
This is already tracked at https://github.com/dotnet/sdk/issues/8792

The solution is outlined here: https://github.com/dotnet/sdk/issues/8792#issuecomment-393756980

Repeated for clarity:

> So to do what you want, you'll need to pass literal double quotes through to MSBuild. On most macOS/Linux shells, this can be accomplished by using single quotes surrounding the double quoted value:
> 
> ```
> dotnet msbuild /p:NoWarn='"1591;1573;3001;3002"'
> ```
> The single quotes will treat both the double quotes and semicolons as literal values, so no need to escape either.
> 
> On Windows, you'll need to use escaped double quotes:
> ```
> dotnet msbuild /p:NoWarn=\"1591;1573;3001;3002\"
> ```

Same error, different property. A fix was attempted, but caused conflicts with other msbuild features, so was rolled back.

**Comment by baronfel** [comment]
I'm going to close this since the root problem is msbuild property syntax on the terminal.
