### ISSUE TITLE
Question: Builds C# in Docker or copies locally built binaries to Docker?

### ISSUE THREAD

**Issue by Cjewett** [dotnet/sdk-container-builds#264]
When running a command like `dotnet publish --os linux --arch x64 -c Debug -p:PublishProfile=DefaultContainer` is this building the code in Docker or is it building on the local machine and then the Docker build copies the binaries into the image? 

The company I work for has been building C# code in Docker and something we wanted to move towards is auto generation of the Dockerfiles. I came across this project and it seemed to be along the lines of what we were looking for, but I noticed when running the above command the bin and obj directories were populated on my local machine. To me that suggests all of the building is occurring on the local machine and it is copying the built binaries into an image, but was hoping if anyone could offer clarification. Is my assumption correct?

Thanks for reading and appreciate any information to help clarify how this works!

**Comment by baronfel** [comment]
That's exactly right - we build your app (targeting it at the specified runtime) and handle creating the container image file system layers and manifests/configuration required to run it purely in .Net. This is exactly what traditional container builders do, just without the additional requirement/capability of a Linux VM to handle RUN commands.

Regarding generating Dockerfiles, there is an open issue in this repo to add a target that would do that (either instead of building the container or in addition to). Would that be useful to you? What would you like to see in a generated Dockerfile?

**Comment by rainersigwald** [comment]
> This is exactly what traditional container builders do,

One big caveat here: if you have a `RUN dotnet build` step in a `Dockerfile`, you'll get the guaranteed-uniform consistent environment of the image you're running in. With SDK-integrated container builds, you are getting the SDK from the host, with less guarantees about always being the exact same version. That gives many benefits but may mean you choose to build in the Dockerfile if that level of locked-downness is important to you.

**Comment by Cjewett** [comment]
@baronfel @rainersigwald Appreciate the responses! I'll create an example repo and explain what we were looking to do over the weekend.

**Comment by baronfel** [comment]
@Cjewett did you get the chance to dig into your needs more? Happy to continue the conversation.

**Comment by Cjewett** [comment]
@baronfel Sorry, hard to get time for open-source these days. Let me create the example now and I'll send it over with an explanation of why we do what we do.

**Comment by Cjewett** [comment]
@baronfel I updated the[ README here](https://github.com/Cjewett/DockerMsBuildExample) which describes how we have been thinking about this problem. I can go into more detail if needed and definitely would love to hear feedback.

**Comment by Cjewett** [comment]
@baronfel I think this ask is similar to https://github.com/dotnet/sdk-container-builds/issues/146 and wouldn't be opposed if you close this out in favor of that. Also if you have any guidance on where one would start to look at in code to step through and start understanding the internals I'm all ears.
