### ISSUE TITLE
ContainerEnvironmentVariable with format like Group:Item throws error

### ISSUE THREAD

**Issue by tpitman** [dotnet/sdk-container-builds#265]
I have an appsettings.json file with this value in it:

`{`
`  "IdentitySettings": {`
`    "Url":"https://myidentityhost.com",`
`    "ClientId":"my-client",`
`}`

I would like to define environment variables in my project file to override the above for production for example.

I created these:

`	<ItemGroup>`
`		<ContainerEnvironmentVariable Include="IdentitySettings:Url" Value="myidentityhost.com"/>`
`		<ContainerEnvironmentVariable Include="IdentitySettings:ClientId" Value="my-client"/>`
`	</ItemGroup>`

I get the following error when I do dotnet publish:

`warning : ContainerEnvironmentVariables: 'IdentitySettings:Url' was not a valid Environment Variable. Ignoring.`

Is there a way to make environment variables like that?

If not how can I override those values in the appsettings.json file using this new container build system?

**Comment by baronfel** [comment]
Environment variables in this tool need to be something that a shell on the host system would accept, and I don't think the format you've shown is valid for that.

Luckily, the Asp.Net configuration system has a pattern for this already - if you replace the `:` with `__` then I think your change should just work. Would you try that and see?

**Comment by tpitman** [comment]
That was an AMAZINGLY fast response and it worked like a charm!

Thanks.

**Comment by baronfel** [comment]
Glad to hear it, and thanks for kicking the tires a bit :)

**Comment by tpitman** [comment]
I just noticed something in the solution window of Visual Studio. Those environment variables show up as items (because they are in an item group). Is there a proper way to hide them?
