### ISSUE TITLE
Steps for container debugging

### ISSUE THREAD

**Issue by gerneio** [dotnet/sdk-container-builds#270]
For VS Code, [here](https://code.visualstudio.com/docs/containers/debug-netcore#_walkthrough) are steps you can follow for debugging a .NET Core project on your local dev machine within a container. Works well, with the caveat that it needs a dockerfile (which can easily be auto-generated using the extension). When performing step #4 from that link, it will add a launch option and a series of tasks for docker run/build. I tried modifying these steps to get it to switch out the build process in favor of the built in SDK flavor via `dotnet publish`, however there were problems since the docker-run task mounts the `/app` directory, which was being used by the `dotnet publish` command (at least that's as much as I can decipher w/o seeing the actual generated dockerfile).

Either way, I think some updated docs could be useful for how to setup for local dev & debugging with VS Code and VS Studio. After spending a couple hours on it, I gave up and switched to just continuing to use the traditional dockerfile approach as explained in the link above.

**Comment by baronfel** [comment]
Thanks @gerneio - I agree that it's a bit rough integrating with the Docker debug tooling in VS Code right now. I opened an issue on their repo to talk about better integration of our solution.
