### ISSUE TITLE
Support alternative container build engines

### ISSUE THREAD

**Issue by clarkezone** [dotnet/sdk-container-builds#271]
Right now this solution is hard coded to docker, it would be nice if it used a provider model to be able to more easily support other container tools such as podman and Kaniko.  Podman is command compatible with docker and would be relatively trivial to support for example.

**Comment by baronfel** [comment]
We work with podman currently if your `podman` binary is aliased to `docker` (I think Podman has docs on this, but I'm not sure), but we should allow for a more first-class way of specifying the engine to push to.

Note that we only use these if you're pushing to a 'local' daemon - if your building/pushing to a remote container registry then no use of Docker/Podman/etc occurs.

**Comment by baronfel** [comment]
This isn't directly on our radar, but we'd definitely accept any contributions towards a provider model + per-tooling implementations. We'd just need to design how to signal the use of each to users via MSBuild properties.

**Comment by baronfel** [comment]
We have more first-class support for podman for all local operations now - this was contributed by @tmds for .NET 8. You can explicitly select your local daemon of choice, or in environments where only podman exists (or podman is aliased to docker) we will use podman directly.

**Comment by atrauzzi** [comment]
@baronfel -- How do you select which daemon?  Right now when I'm in a github action and I'm trying to use podman, it favours docker.  It's not clear how to tell the publish action to favour podman?

**Comment by baronfel** [comment]
@atrauzzi Set the `LocalRegistry` MSBuild property to `Podman` to force the usage of podman. Looks like we're missing documentation for this property at [our reference docs](https://learn.microsoft.com/en-us/dotnet/core/containers/publish-configuration), so I'll log an issue for that now.

EDIT: Logged https://github.com/dotnet/docs/issues/45171 for tracking this gap.

**Comment by atrauzzi** [comment]
Appreciate it!  And thanks for the quick reply 🙂 

Love this functionality. 💯
