### ISSUE TITLE
Different behavior between os/arch and runtimeidentifier when publishing aspnet applications

### ISSUE THREAD

**Issue by peter-dolkens** [dotnet/sdk-container-builds#276]
If I build a net6.0 web application with the following command, I get the expected result:

```
dotnet publish --os linux --arch x64
MSBuild version 17.4.0+18d5aef85 for .NET
...
Building image 'dotnet/imagename' with tags laster on top of base image mcr.microsoft.com/dotnet/aspnet:6.0
Pushed container 'dotnet/imagename:latest' to Docker daemon
```

However, if I use the `--runtime` argument, instead of `--os` and `--arch`, different behavior is observed:
```
dotnet publish --runtime linux-x64
MSBuild version 17.4.0+18d5aef85 for .NET
...
Building image 'dotnet/imagename' with tags laster on top of base image mcr.microsoft.com/dotnet/runtime-deps:6.0
Pushed container 'dotnet/imagename:latest' to Docker daemon
```

I would have expected these arguments to be equivalent unless I'm missing something?

**Comment by baronfel** [comment]
That's really interesting - can you take a binlog (add the -bl parameter) to each of those examples and dig in a bit? I'm especially interested in what the `ParseContainerProperties` task returned.

**Comment by peter-dolkens** [comment]
Will do in 1 moment - looks like I'm getting `_IsSelfContained` set to `true` in `packaging\build\Microsoft.NET.Build.Containers.targets` for some reason, so I'll try and track that too.

**Comment by baronfel** [comment]
My guess is a gap in the .NET SDK's CLI argument handling - specifying a runtime currently means setting self-contained to true (we are reevaluating thing), and I bet that the logic there isn't unified with the `--arch` and `--os` flags.

**Comment by peter-dolkens** [comment]
Good guess - right up the top of the log files before we go anywhere near sdk-container-builds

```
Command line arguments = "C:\Program Files\dotnet\sdk\7.0.101\MSBuild.dll -maxcpucount -verbosity:m -restore -target:Publish --property:_IsPublishing=true --property:PublishProfile=DefaultContainer --property:ContainerImageTag=latest -property:RuntimeIdentifier=linux-x64 -property:_CommandLineDefinedRuntimeIdentifier=true -verbosity:diag -m:1 -bl -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\7.0.101\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\7.0.101\dotnet.dll"
```

vs

```
Command line arguments = "C:\Program Files\dotnet\sdk\7.0.101\MSBuild.dll -maxcpucount -verbosity:m -restore -target:Publish --property:_IsPublishing=true --property:PublishProfile=DefaultContainer --property:ContainerImageTag=latest -verbosity:diag -property:RuntimeIdentifier=linux-x64 -property:SelfContained=false -m:1 -bl -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\7.0.101\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\7.0.101\dotnet.dll"
```

Using `--os` appears to set SelfContainer=false by default, but `--runtime` doesn't.

**Comment by peter-dolkens** [comment]
Happy to close this - it's not a blocker, just wanted to flag so your team was aware.

**Comment by baronfel** [comment]
@nagilson when you have a sec we should talk about these flags and how/if we could unify the behavior on the CLI

**Comment by nagilson** [comment]
Yes, we could likely do this by adding `SetForwardingFunction(ResolveArchOptionToRuntimeIdentifier)` to `--runtime`. But in .net 8 after we discuss in partner sync we may not need to do this anyway as it will be done in MSBuild.

**Comment by baronfel** [comment]
That was my thought, but I was wondering if we needed to do a servicing fix for 7.x to unify the behavior?

**Comment by baronfel** [comment]
This was a gap that I believe we have closed in the SDK.
