### ISSUE TITLE
Bad error experience when pushing to local Docker that isn't running

### ISSUE THREAD

**Issue by lbruun** [dotnet/sdk-container-builds#278]
The [original announcement](https://devblogs.microsoft.com/dotnet/announcing-builtin-container-support-for-the-dotnet-sdk/) says the new feature is inspired by [Jib](https://github.com/GoogleContainerTools/jib) in the Java ecosystem, [Ko](https://github.com/google/ko) for Go, however those project's main selling point (I think) is that they do not require a docker daemon to be running in order to create the OCI image.  Because of the reference, I thought the same would be true for this project.

Alas, that is not the case. A running docker daemon is absolutely needed for `dotnet publish ...`  and to make matters worse the error you get if it is not running, is rather weird to dechiper.

Is building the OCI image without requiring a docker daemon on the roadmap? I'm asking because it seems to be almost there, especially by saying that emulating Dockerfile `RUN` is not in scope of this project, etc.

**Comment by lippertmarkus** [comment]
Docker Daemon isn't required if you specify a `ContainerRegistry` and `ImageName`:
```
dotnet publish -p:PublishProfile=DefaultContainer -p:ContainerRegistry=myregistry.io -p:ContainerImageName=lippertmarkus/mywebapi
```

I wrote about that here: https://lippertmarkus.com/2022/12/09/dotnet-7-container-support/

**Comment by lbruun** [comment]
Thanks. Got it.

**Comment by baronfel** [comment]
A good takeaway from this is that we could log a message about _why_ the local docker daemon is in use, and we should try to handle the 'no daemon found' error case in a nicer manner.

**Comment by rainersigwald** [comment]
> A good takeaway from this is that we could log a message about _why_ the local docker daemon is in use, and we should try to handle the 'no daemon found' error case in a nicer manner.

Reactivating to track these improvements.
