### ISSUE TITLE
Is linux-arm64 on the roadmap

### ISSUE THREAD

**Issue by stefc** [dotnet/sdk-container-builds#281]
error CONTAINER006: The Microsoft.NET.Build.Containers package does not (yet) support publishing for linux-arm6

I want to build a container running on a Kubernetes ARM cluster potentially. 

Is this on the roadmap

**Comment by baronfel** [comment]
Yes, we have an open PR that brings support for other runtime identifiers: #247

We hope to have it merged soon.
