### ISSUE TITLE
Produce an image as .tar.gz

### ISSUE THREAD

**Issue by stan-sz** [dotnet/sdk-container-builds#283]
Can the SDK produce the docker image as a local .tar.gz as in `docker save` comand?

**Comment by baronfel** [comment]
Not yet, but it's definitely something that is doable. Jib does it, for example. Is this something you'd be interested in digging into? We'd need

* a way to signal this from MSBuild properties
* a new 'output' mechanism in the `CreateNewImage` build task that would stream the generate archive similar to the existing `Docker.Load` API, but directly to a file.

**Comment by stan-sz** [comment]
Thanks for the hints. I cannot dig to it at the moment, but it's up-for-grabs for anyone willing to.

**Comment by MattKotsenas** [comment]
This is something I'd be interested in as well. I'm new to this project, but if it's something that is easy for a new person to get ramped up on, I'd be willing to contribute here.

**Comment by Danielku15** [comment]
I opened a proposal for a new option here: https://github.com/dotnet/sdk-container-builds/pull/375 

I have successfully used a similar approach on my earlier changes where I added the Windows Container Support and fixed the Tar format writing for LCOW. 

There are still some design decisions to take but the PR might give a base for discussion:

* How to handle the multiple output file naming (is it even needed to have multiple tars for all 'destinations')
* New dedicated option vs. a local file `ILocalDaemon`
* (anything else?)

**Comment by stan-sz** [comment]
Thank you @Danielku15!

**Comment by baronfel** [comment]
Closing because @Danielku15 implemented this in https://github.com/dotnet/sdk/pull/35151
