### ISSUE TITLE
Please support NativeAOT even if experimental

### ISSUE THREAD

**Issue by kant2002** [dotnet/sdk-container-builds#288]
Create NativeAOT application on Windows and make sure that you have reference and specify basic container properties.
```
<ItemGroup>
    <PackageReference Include="Microsoft.NET.Build.Containers" Version="0.2.7"/>
</ItemGroup>

<PropertyGroup>
    <ContainerImageName>dotnet-webapp-chiseled-trimmed-singlefile-invariant</ContainerImageName>
    <ContainerImageTag>1.1.0</ContainerImageTag>
    <ContainerBaseImage>mcr.microsoft.com/dotnet/nightly/runtime-deps:6.0-jammy-chiseled</ContainerBaseImage>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
</PropertyGroup>
```
Then attempt to publish docker container
```
dotnet publish --os linux --arch x64 -p:PublishProfile=DefaultContainer -c Release
```

You will receive error
```
Microsoft.NETCore.Native.Publish.targets(58,5): error : Cross-OS native compilation is not supported.
```

NativeAOT does not support compiling on Windows for Linux, and thus we have this error. I know that Web projects not yet supported by NativeAOT, but they are working for a long time if you need it. And this combination allow to have smaller images. Would be great to have something which unlock this scenario.

**Comment by baronfel** [comment]
The docs on NativeAoT explicitly call out that cross-os compilation [is not supported](https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/compiling.md#cross-architecture-compilation), so I'm not sure what could be done here to get around that. If that restriction is ever lifted then of course we'd plug right in! If you'd like to see Cross-os NativeAOT  I encourage you to open an issue or discussion at https://github.com/dotnet/runtime about it!

Thank you for the report.
