### ISSUE TITLE
ContainerEnvironmentVariable does not support digits

### ISSUE THREAD

**Issue by jpiquot** [dotnet/sdk-container-builds#290]
It does not seem that digits are supported in environment variables. Is this by design or a bug? 

```
	<ItemGroup>
		<ContainerEnvironmentVariable Include="D3Name" Value="a-name" />
	</ItemGroup>
```

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/6775094/212562772-3574ba14-876f-40ac-ae3b-361679e8313d.png">

**Comment by baronfel** [comment]
I think this is a bug - we do want to warn users if they try to add environment variables that aren't usable on the destination system, but it looks like our Regex is a bit off: https://github.com/dotnet/sdk-container-builds/blob/e5697841ca74fe00255a42a2039b79ea272c064f/Microsoft.NET.Build.Containers/ContainerHelpers.cs#L27

I think this should change to only verify that the first character is an alpha character - the remainder can be alphanumeric, dash, underscore (I think that covers it).
