### ISSUE TITLE
Container Customization via .csproj file doesn't work

### ISSUE THREAD

**Issue by domsew** [dotnet/sdk-container-builds#295]
Hi, when I build a container without MSBuild properties it works as expected. But when I try to add some properties, the container image is not pushed to local docker daemon.
```csproj
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.0.1</Version>
    <ContainerImageName>demo-web-api</ContainerImageName>
    <ContainerImageTags>@(Version);latest</ContainerImageTags>
  </PropertyGroup>
</Project>
```
How to make it work?

**Comment by baronfel** [comment]
Can you get an https://aka.ms/binlog and add it here?  That would help figure out what's up with your setup.

**Comment by domsew** [comment]
[msbuild.zip](https://github.com/dotnet/sdk-container-builds/files/10436341/msbuild.zip)
I think that the problem is only related to ContainerImageTags property. It doesn't matter what we put there.

**Comment by baronfel** [comment]
Ah, there was a bug in that property specifically that we've fixed but not pushed in a stable version yet. You should be able to use the prereleases from GitHub Packages, or wait for a short time - we're hoping to do another stable release to NuGet this week.

**Comment by domsew** [comment]
It works for me with alpha version. Thank you.
Btw. I wanted to ask if is it possible to reuse `Version` property? I want to do this:
```csproj
<Version>0.0.1</Version>
<ContainerImageTags>@(Version);latest</ContainerImageTags>
```
instead of this:
```csproj
<Version>0.0.1</Version>
<ContainerImageTags>0.0.1;latest</ContainerImageTags>
```

**Comment by rainersigwald** [comment]
> Btw. I wanted to ask if is it possible to reuse `Version` property? I want to do this:
> 
> ```
> <Version>0.0.1</Version>
> <ContainerImageTags>@(Version);latest</ContainerImageTags>
> ```

Yes but reference it with `$(Version)` because that's a property, rather than an item.

**Comment by samtrion** [comment]
> Yes but reference it with `$(Version)` because that's a property, rather than an item.

```xml
  <PropertyGroup>
    <ContainerImageName>myproject/api</ContainerImageName>
    <ContainerImageTags>latest;_$(Version)</ContainerImageTags>
  </PropertyGroup>
```

Unfortunately this does not work at the moment, because the resolution of `$(Version)` is `string.Empty`.


```
Building image 'myproject/api' with tags latest,_ on top of base image mcr.microsoft.com:443/dotnet/aspnet:7.0
  Pushed container 'myproject/api:latest' to local daemon
  Pushed container 'myproject/api:_' to local daemon
```
