### ISSUE TITLE
Can't reference package nightly build in project with EnableSdkContainerSupport

### ISSUE THREAD

**Issue by flcdrg** [dotnet/sdk-container-builds#299]
In a project with `EnableSdkContainerSupport` property set (eg. when created with the Visual Studio Publish wizard), you can't then add a package reference to the nightly build. It fails with the following error:

```text
info : Restoring packages for C:\dev\sandbox\WebApplication10\WebApplication10\WebApplication10.csproj...
info : Package 'Microsoft.NET.Build.Containers' is compatible with all the specified frameworks in project 'C:\dev\sandbox\WebApplication10\WebApplication10\WebApplication10.csproj'.
error: Error while performing Update for package 'Microsoft.NET.Build.Containers'. Cannot edit items in imported files -
error:   Item 'PackageReference' for 'Microsoft.NET.Build.Containers' in Imported file 'C:\Program Files\dotnet\sdk\7.0.200-preview.22628.1\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props'.
```

Not sure if this is something that can be fixed, or just will need to be documented to either comment out the property or set it to false.

**Comment by baronfel** [comment]
This is definitely not the intended experience - will chat with the team and see if we can squeak in a change for the 7.0.2xx series here. Otherwise you may need to workaround by setting `EnableSdkContainerSupport` to `false`. This will definitely be solved by the time we integrate into the SDK properly for 7.0.3xx, though.

@vijayrkn - heads up that users can't float the versions like we thought.

**Comment by vijayrkn** [comment]
For the package reference issue, if you change the include to update, does it work?
`<PackageReference Update=`

**Comment by rainersigwald** [comment]
You could also change the version reference with a property

```xml
<SdkContainerSupportPackageVersion>0.3.2</SdkContainerSupportPackageVersion>
```

We should definitely call this out very explicitly in the blog post @baronfel.

**Comment by flcdrg** [comment]
@vijayrkn FYI I just tested using `<PackageReference Update="Microsoft.NET.Build.Containers" Version="0.3.2" />`, and that also failed with an error:

```text
C:\Users\david\.nuget\packages\microsoft.net.build.containers\0.3.2\build\Microsoft.NET.Build.Containers.targets(130,25): Error MSB4064: The "ContainerRuntimeIdentifier" parameter is not supported by the "CreateNewImage" task loaded from assembly: Microsoft.NET.Build.Containers, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null from the path: C:\Users\david\.nuget\packages\microsoft.net.build.containers\0.2.7\tasks\net472\Microsoft.NET.Build.Containers.dll. Verify that the parameter exists on the task, the <UsingTask> points to the correct assembly, and it is a settable public instance property.
C:\Users\david\.nuget\packages\microsoft.net.build.containers\0.3.2\build\Microsoft.NET.Build.Containers.targets(114,9): Error MSB4063: The "CreateNewImage" task could not be initialized with its input parameters. 
```

**Comment by baronfel** [comment]
Closing this because it's been covered.
