### ISSUE TITLE
Support non-admin credentials for ACR

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#310]
This needs further investigation, but ACR does a token-based auth that appears to be an AAD login. The docker credential provider, as well as the `az acr` login command, both do this dance and give users a nice `docker login`-esque experience. 

Currently we do not detect and do this dance - we will likely need to build an ACR-specific delegating handler in the style of the one that was made for AWS ECR and handle any ACR quirks in it.

**Comment by baronfel** [comment]
Closing this as we support this per Antonio's testing.

**Comment by mikocot** [comment]
> Closing this as we support this per Antonio's testing.

does it work only in the current main branch or already in v0.3.2 that was released?

**Comment by baronfel** [comment]
That should be available in the 0.4.0 release, out currently.
