### ISSUE TITLE
Multiple tags aren't properly recognized

### ISSUE THREAD

**Issue by milten89** [dotnet/sdk-container-builds#311]
I've found error with parsing multiple containers tag. 

[This](https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container#containerimagetags) example shows that I can use **;** (semicolon) to separate tags like this `<ContainerImageTag>1.2.3-alpha2;latest</ContainerImageTag>`, but when I use it in a project and try to publish it I get `error CONTAINER004: Invalid ContainerImageTag provided: 1.2.3-alpha2;latest. Image tags must be alphanumeric, underscore, hyphen, or period.`

I've tried separate them 
```
<ContainerImageTag>1.2.3-alpha2</ContainerImageTag>
<ContainerImageTag>latest</ContainerImageTag>
```
but only last **ContainerImageTag** is used

Passing it in arguments `dotnet publish --os linux --arch x64 -c Release -p PublishProfile=DefaultContainer -p ContainerImageTag=1.2.3-alpha2%3Blatest` throws error as well.

I'm using **Microsoft.NET.Build.Containers** version **0.3.2**

**Comment by baronfel** [comment]
Can you try with the ContainerImageTags property instead? There's a plural version I think you're meaning to use.

**Comment by asankaf** [comment]
Using `-p:ContainerImageTags` didn't help me either.

![image](https://user-images.githubusercontent.com/1999525/215107715-08cd0d9c-1b94-4a1d-ab01-25fb9d2b21bd.png)

**Comment by baronfel** [comment]
@asankaf I think what you're hitting now is MSBuild property escaping syntax oddities - this is a general problem: https://github.com/dotnet/msbuild/issues/471

Since you're using pwsh, the answers on that thread should help you out.

**Comment by milten89** [comment]
`ContainerImageTags` works. Maybe next time this kind of problem should give more descriptive errors, or maybe not implementing two configuration tags that are doing exactly the same thing (`ContainerImageTag` and `ContainerImageTags` works exactly the same for a single tag). The current situation is at least suboptimal and deceptive.
