### ISSUE TITLE
Investigate changes and support for Visual Studio Docker tooling

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#312]
We integrate with publish well, but the story for inner-loop development (especially f5 debugging) probably needs some improvement. We should interface with the team and determine what they need from us in order to integrate.

**Comment by baronfel** [comment]
Closing as our partner team has launched their support for our tech!

**Comment by ggirard07** [comment]
Do you have details like link to relevant issues or documentation about what will be/is supported here?

**Comment by baronfel** [comment]
VS Code supports building and running (with debugging) inside a container using our tech just by pressing F5 - you can read more about that [in this blog post](https://devblogs.microsoft.com/dotnet/debugging-dotnet-containers-with-visual-studio-code-docker-tools/). VS is on track to implement the same.

**Comment by ggirard07** [comment]
I am looking more precisely for VS, especially if there is anything possible while keeping their support for docker-compose too
