### ISSUE TITLE
Enable `HEALTHCHECK` with SDK Containers

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk-container-builds#316]
Over at dotnet/dotnet-docker, we're looking into health checks. It started with needing to enable the scenario in distroless containers due to that being hard (installing `curl`) and now we're realizing that the same is true (for different reasons) with SDK-built containers. We decided that we'd do the feature if we could establish a partnership with the SDK team to enable a full E2E.

Context: https://github.com/dotnet/dotnet-docker/issues/4300

This is what we've come up with so far, with `wget` and `curl` (since these tools are available in various places).

Using `curl`, which comes with Nano Server and is likely the most common tool to use:

```Dockerfile
HEALTHCHECK CMD curl -sf --show-error http://localhost:80/healthz || exit 1
```

Using `wget`, which comes with Alpine images:

```Dockerfile
HEALTHCHECK CMD wget -qO- -t1 http://localhost:80/healthz || exit 1
```

That all looks great. The challenge is that these tools are often not available and they also add size and vulnerability risk. A simple framework-dependent tool could serve the same purpose w/o any of those problems.

Instead, the following would be generated for you:

```Dockerfile
HEALTHCHECK CMD httpclient http://localhost:80/healthz || exit 1
```

The basic idea is that we'd develop a tool and push to blob storage. Similar to: https://github.com/microsoft/dotnet-framework-docker/blob/9715ee1b646522ea91d62ac1b6009e778d016abf/src/aspnet/4.8.1/windowsservercore-ltsc2022/Dockerfile#L10. The SDK would then expose a property like `EnableHealthChecks`, which would then install the tool and add the `HEALTHCHECK` directive.

There is an open question of whether `HEALTHCHECK` is even useful in 2023. It enables observing health via `docker ps` and `docker inspect`.

- `docker ps`:  https://github.com/dotnet/dotnet-docker/pull/4352#issuecomment-1402616482
- `docker inspect`: https://github.com/dotnet/dotnet-docker/pull/4352#issuecomment-1405809053

It's most useful for dev (for folks that do dev with Docker) and for appliance style apps like Pi-Hole. The people asking for this seem to be invested in Docker desktop and/or compose.

Pi-hole use case:

- https://github.com/pi-hole/docker-pi-hole/blob/79f96060b6d896a02011a1ad7567c77c6a831378/src/Dockerfile#L39
- https://github.com/pi-hole/docker-pi-hole/blob/master/examples/docker-compose.yml.example

Is the SDK team interested in partnering on this scenario? I think the project is relatively small, however, I think it's also really just nice-to-have. For the SDK team, it certainly would help expand the tech to more scenarios. We're unlikely to do this feature w/o partnering with the SDK team. We want to either enable an E2E or just provide customers with guidance.

Note: the port thing can be a challenge. We'd need to sort that out. Context: https://github.com/dotnet/dotnet-docker/issues/3968.

**Comment by richlander** [comment]
Transfered the issue. Good call.

We could expand this to other tools, like `dotnet-dump`. That could be very nice.

Interesting. You'll see that we were considering the second option (kinda) in https://github.com/dotnet/dotnet-docker/issues/4300. We're definitely happy to collaborate on both options. I see why the second one might be better.

**Comment by richlander** [comment]
Any idea when you folks will make a decision on whether this is a scenario you plan to take on in the .NET 8 cycle?

**Comment by Kralizek** [comment]
I'm very interested in having health check support in SDK containers for better integration with AWS ECS hosting.

**Comment by baronfel** [comment]
We're not going to lean into healthcheck support in the SDK container tooling itself because this extension is Docker-only and has no support in OCI images, which the container world is moving towards.

**Comment by mthalman** [comment]
> We're not going to lean into healthcheck support in the SDK container tooling itself because this extension is Docker-only and has no support in OCI images, which the container world is moving towards.

This issue is about more than just `HEALTHCHECK`. It's also about potentially injecting a tool to do the execution of the check, which would still be relevant in K8s scenarios with a probe configuration. Just want to make sure that is considered before closing for good.

**Comment by baronfel** [comment]
@mthalman to me that sounds a bit like https://github.com/dotnet/sdk-container-builds/issues/325 - if you have a layer with the content in some content addressable store, then the tooling should let you inject that layer and incorporate it into the final product. This is how google did debugging tools for JVM apps in the original Jib presentations a few years ago, and I believe Oryx does the same thing when keeping image runtimes green.
