### ISSUE TITLE
Fail with yikes message when Docker desktop not running

### ISSUE THREAD

**Issue by timheuer** [dotnet/sdk-container-builds#318]
I hadn't noticed my local Docker daemon wasn't running (it always is) and I was getting failures during publish with this target.  I finally paid attention to the stack dump and saw it was failing here.

It looks like earlier there should be a catch if Load() would fail or something, but opportunity to catch that exception earlier, spew a friendlier message.

https://github.com/dotnet/sdk-container-builds/blob/fb658daa93fc680ea3cedeb46ac031da2cb4e490/Microsoft.NET.Build.Containers/LocalDocker.cs#L57

**Comment by baronfel** [comment]
Definitely agree - we've got https://github.com/dotnet/sdk-container-builds/issues/278 open to track this specifically. Error messages all up are something we plan to get really solid for the 7.0.3xx timeframe currently.

**Comment by baronfel** [comment]
Going to close this as a duplicate of #278 as a result.
