### ISSUE TITLE
Try to move property inference to evaluation time

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#321]
Part of #309.

The partner request is to move base image inference especially to evaluation time. I don't think that will be possible due to the import order of the SDK. Some context:
* we need to know if the project is an AspNetCore project, which we do by checking the ProjectCapabilties
* ProjectCapabilities for AspNetCore are set during the WebSDK target imports
* WebSDK target imports happen after .NET SDK target imports
* .NET SDK target imports are the things that do NuGet package target imports
* We are part of NuGet package target imports
 
Graphically:
![image](https://user-images.githubusercontent.com/573979/216437661-99c0a95b-8aa4-4ef2-8287-10c708fbbdd4.png)

We need to communicate with our partner teams in VS/VSCode Docker tooling to find another solution to their request, I think.

**Comment by rainersigwald** [comment]
The order could potentially be changed after this is part of the SDK.

The web sdk could also put a marker property in `Microsoft.NET.Sdk.Web\Sdk\Sdk.props`, super early in the import order, that we key off of instead of the capability (which is generally VS focused and feels slightly wrong here).

**Comment by rainersigwald** [comment]
Actually it looks like there's already `$(UsingMicrosoftNETSdkWeb)` -- is that sufficient for us?

**Comment by baronfel** [comment]
The only concern I had with that path @rainersigwald is that it is possible for someone to add a `FrameworkReference` to the ASP.NET Shared Framework directly without adding the Web SDK, and still technically have a viable web-enabled application. So a compound condition like `'$(UsingMicrosoftNETSDKWeb)' == 'true' or (@(FrameworkReference00->Count()) > 0 and @(FrameworkReference->AnyHaveMetadataValue('Identity', 'Microsoft.AspNetCore.All')))'` or whatever the specific shared framework name is.

**Comment by baronfel** [comment]
This was recently contributed in #356
