### ISSUE TITLE
Convert Registry readonly public fields to properties with explicit getter/init behavior

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#330]
property would be better, as it gets public; better read-only if never changed.

_Originally posted by @vlada-shubina in https://github.com/dotnet/sdk-container-builds/pull/319#discussion_r1096321506_

This is found by CA1051, which we should enable as part of the PR solving this.

**Comment by vlada-shubina** [comment]
Also address: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1051
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2211 - Non-constant fields should not be visible in scope of this issue.
