### ISSUE TITLE
Change `containerize.exe`'s console output to adhere to the MSBuild canonical format

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#331]
Currently, errors reported from container building that occur from inside VS (and as a result invoke the `containerize` tool) do not have good error formatting. This is because much of the output from the `containerize` tool doesn't match the [MSBuild Canonical Error Format](https://github.com/dotnet/msbuild/blob/main/src/Shared/CanonicalError.cs). We should change this so that every warning and error reported from this tool has codes, file and line information, etc - as much as possible the same output as the net7.0 output.

**Comment by vlada-shubina** [comment]
From discussion:
- canonical error format doesn't support help links
- TODO: check if VS has a fallback to link in specific format
- consider adding help link to canonical error format (needs to be done in MSBuild). This can be beneficial as terminal now supports links.

**Comment by baronfel** [comment]
I added the blocked label because currently the VS Publish output doesn't respect the MSBuild canonical error format. We've got a conversation going with our VS Partners on the Publish team to dig in further.

**Comment by baronfel** [comment]
We've implemented this, but VS publish separately needs to handle this. Our side is done.
