### ISSUE TITLE
Ensure unique codes for all `Log.LogError/Log.LogWarning` calls

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#365]
Just to double check, are logged errors, https://github.com/dotnet/sdk-container-builds/blob/cbaba1ca0632ca1b9d49b1e928102890ee3f55fe/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs#L63 for example, to be done in separate PR?

_Originally posted by @vlada-shubina in https://github.com/dotnet/sdk-container-builds/issues/357#issuecomment-1442149106_

**Comment by vlada-shubina** [comment]
also those messages should be localised.
