### ISSUE TITLE
Default .NET 8 container images to use the `app` user

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#373]
Requires https://github.com/dotnet/sdk-container-builds/issues/115 and https://github.com/dotnet/sdk-container-builds/issues/198.

For .NET 8 Containers Microsoft provides a non-root user named `app`. We should default folks into running rootless, so we should set `ContainerUser` according to the following decision tree. 

* the `ContainerBaseImage` is dotnet/runtime-deps, dotnet/runtime, or dotnet/aspnet and
* the `ContainerImageTags` contains any 8.0 tag (including previews and/or rc tags) then
* if the `ContainerRuntimeIdentifier` is a Windows RID then use `ContainerUser`, else if the `ContainerRuntimeIdentifier` is a Linux RID then use `app`, otherwise
* do not set the `ContainerUser`

**Comment by richlander** [comment]
I'm not sure if sdk-container-builds supports Windows. For Windows, we are not adding `app` but plan to rely on `ContainerUser`, which already exists there. We could infer that, or the user would write `<ContainerUser>ContainerUser</ContainerUser>`. Fun!

**Comment by baronfel** [comment]
We do not currently due to but hopefully will thanks to https://github.com/dotnet/sdk-container-builds/pull/343, so we should be forward-looking here as well.  Updated the OP with the Windows User and scenario.

**Comment by baronfel** [comment]
Per https://github.com/dotnet/dotnet-docker/issues/4451#issuecomment-1461147544, we should bias towards using the user id instead of the user name for our home-grown users (and probably also document that some engines like Kubernetes work better with ids), and so we should use 64198 instead of `app` in our targets. We should put a comment alongside so that the reason for the value isn't lost.

**Comment by richlander** [comment]
I will have more content written on this topic soon.

**Comment by richlander** [comment]
FYI: https://github.com/dotnet/dotnet-docker/pull/4508

**Comment by baronfel** [comment]
Thanks for the heads-up, will extract this to a separate issue.
