### ISSUE TITLE
Change Request: One Image for all tags

### ISSUE THREAD

**Issue by Danielku15** [dotnet/sdk-container-builds#379]
As part of #375  I realized that sdk-container-builds creates a new image for every tag. I think it would be better to create only one single tar.gz with all tags set. This would: 

* Reduce the load needed to generate the tar
* Reduce the load on the daemon side as only 1 docker load needs to happen
* Eliminate the problem that one application currently has N output tars. 

The change should be valid from a [Docker Image Specification v1.2.0](https://github.com/moby/moby/blob/master/image/spec/v1.2.md) side.

**Comment by baronfel** [comment]
I agree, this would be a good change.

Separately, for the registry push code path we regenerate the entire image for each tag (this was very simple to add when it was initially done). I think we should instead push the layer and manifest blobs, and then push each separate tag blob. That would be a large performance improvement for multi-tag pushes.

**Comment by baronfel** [comment]
Closing this as @Danielku15 contributed it in https://github.com/dotnet/sdk/pull/35138 for the .NET 8 release.
