### ISSUE TITLE
Use with 3rd party images

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk-container-builds#397]
We'd like this tooling to work well with the .NET images that are shipped an supported by Red Hat.

I just tried setting:
```xml
<ContainerBaseImage>registry.access.redhat.com/ubi8/dotnet-70:7.0</ContainerBaseImage>
```
And I could build an run the resulting image:
```
$ podman run -ti web:1.0.0
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
^Cinfo: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
...
```
Can we capture the expected requirements for a base image in a document?

cc @baronfel @richlander @omajid @aslicerh

**Comment by tmds** [comment]
> Overall I'd love it if RedHat wanted to ship an 'extension' package or something for this tech that modified the base image inference/entrypoint/etc in ways that make sense for your images!

Yes, the goal is to have our images work with this tooling, and make it easy for the user to opt-in to using them.

> right now the requirements are as follows:

This is already a good overview to start from.

Can we capture these in a document, and try improve them as we enable the tooling to work with the Red Hat images?

**Comment by richlander** [comment]
This sounds like an awesome direction. Having this system work well for RH-produced images is a great idea.

Perhaps this is something that Canonical folks would be interested in as well.

**Comment by tmds** [comment]
The 8.0 tooling works wel with Red Hat images.

The changes we made weren't Red Hat specific, and will improve the SDK for working with other base images too.
