### ISSUE TITLE
Improve non-web project publish to container

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/sdk-container-builds#402]
At the moment the following steps are needed to publish non-web (for example console) app to container:
- add a `PackageReference` to `Microsoft.NET.Build.Containers`
- run publish with additional target `PublishContainer`

Consider improvements to this scenario to make the experience seamless.
Open considerations:
given that we will include containers tasks\targets to publish SDK
- can we enable the publish SDK for all project types by default? (likely no)
- if we can't enable it by default, is there some mechanism that we can use to infer when we can enable it?
- if we do enable it by default, there are certain project types that do not work with it (e.g. WPF/Winforms) - need to work with them to turn the flag 'off' for them

If none of above is feasible, a manual step of including publish SDK may be needed

```
<Project Sdk="Microsoft.NET.Sdk">
```
to
```
<Project Sdk="Microsoft.NET.Sdk;Microsoft.NET.Publish.Sdk">
```

**Comment by baronfel** [comment]
Closing in favor of #141.
