### ISSUE TITLE
Make a test that verifies that all of the runtime dependencies in containerize's runtime deps.json are packaged

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/sdk-container-builds#405]
We should make a test that verifies that all of the runtime dependencies in containerize's runtime deps.json are packaged - this kind of error happens every time we change dependencies (like I did with NuGet recently!)

_Originally posted by @baronfel in https://github.com/dotnet/sdk/pull/31542#discussion_r1153375041_

**Comment by baronfel** [comment]
We did this!
