### ISSUE TITLE
Microsoft.NET.Build.Containers versions above 0.4.0 are not available on nuget.org

### ISSUE THREAD

**Issue by petre-c** [dotnet/sdk-container-builds#407]
Versions above 0.4.0 are not available on nuget.org.

None of the below works:
```bash
dotnet add package Microsoft.NET.Build.Containers --version 0.5.0-alpha.1   
dotnet add package Microsoft.NET.Build.Containers --version 0.4.1
```

```
error: NU1102: Unable to find package Microsoft.NET.Build.Containers with version (>= 0.5.0-alpha.1)
error:   - Found 4 version(s) in nuget.org [ Nearest version: 0.4.0 ]
```

**Comment by petrechitashvili** [comment]
Does this apply to version `0.4.1` as well?

Consuming from source `https://nuget.pkg.github.com/dotnet/index.json` from an outsider's perspective is uneasy as it requires authentication.

**Comment by vlada-shubina** [comment]
New versions are now available: https://www.nuget.org/packages/Microsoft.NET.Build.Containers/

Now `Microsoft.NET.Build.Containers` is released together with .NET SDK (including previews) and versioned accordingly.

**Comment by petre-c** [comment]
> New versions are now available: https://www.nuget.org/packages/Microsoft.NET.Build.Containers/
> 
> Now `Microsoft.NET.Build.Containers` is released together with .NET SDK (including previews) and versioned accordingly.

Great, thank you very much 🙏🏽
