### ISSUE TITLE
Does it support Azure function apps at all?

### ISSUE THREAD

**Issue by findajay** [dotnet/sdk-container-builds#411]
Is it possible to containerize azure function apps using this sdk ?

**Comment by baronfel** [comment]
Hi @findajay - do you have a sample application we could try? I looked at some existing Azure Functions documentation [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image?tabs=in-process%2Cbash%2Cazure-cli%2Cv1&pivots=programming-language-csharp) which suggests that isolated Azure Functions have to use a specific base image. If that's all that is required you could try pointing to that specific base image by using the `ContainerBaseImage` MSBuild property.  In the meantime we can reach out to our partner teams about a more deep integration.

**Comment by findajay** [comment]
@baronfel Thanks for your response. I have tried using mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated6.0 this base image for .net6 isolated function app and it does not work for me. I will upload the code to my GitHub and share the link but I am not doing anything special, just created a new .net6 isolated function app using visual studio and tried building container image using sdk-container.

**Comment by findajay** [comment]
@baronfel Here is the sample app https://github.com/findajay/functionwithdocker/tree/master/functionwithdocker. In this app I am able to generate container image using docker but not by using skd container dotnet publish.

**Comment by findajay** [comment]
@baronfel Can you prioritize this issue in June 30 milestone. We have been waiting a long for this? Thanks

**Comment by baronfel** [comment]
I did a sample of what integration with AzureFunctions might look like in [this gist](https://gist.github.com/baronfel/e97f46933d05365ea93d7855af742e58) - this is something the Azure Functions team would be involved in maintaining, though.

**Comment by findajay** [comment]
@baronfel Thanks for taking time and focus on this. I hope azure functions team will take it up.

**Comment by baronfel** [comment]
I need to reach out to them to make their getting-started templates compatible with our tech anyway, so I expect this will come up :)

**Comment by ggirard07** [comment]
How can I track the progress on this? Is it going to be part of this issue or in another one on the functions team side? Thanks!

**Comment by findajay** [comment]
I think changes has been done as part of this ticket https://github.com/dotnet/sdk-container-builds/issues/402. Not sure if they reached destination repository or not. @baronfel Could you please confirm this if possible ?

**Comment by baronfel** [comment]
No, #402 is about publish profile support for console applications, not Azure Functions support for this tech.

**Comment by baronfel** [comment]
If this would be useful for you, please check out the issue I created on the azure-functions-core-tools repo: https://github.com/Azure/azure-functions-core-tools/issues/3355

**Comment by baronfel** [comment]
Closing as the Functions team has implemented support and will be releasing it soon.

**Comment by ggirard07** [comment]
Is there any reference/version number we could track to determine when this is going to be publicly available?

**Comment by baronfel** [comment]
https://github.com/Azure/azure-functions-dotnet-worker/pull/2671 Here's the PR on their side that implemented the support. It looks like this is in preview 2 of the 2.0 version of the functions SDK, which is already released: https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/2.0.0-preview2

**Comment by ajay-apcoa** [comment]
Thanks for implementing this interesting feature.
