### ISSUE TITLE
Pushes to ACR from Visual Studio are slow

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#412]
I've received feedback from a few users that pushes of reasonably-sized layers (100-400MB) is very slow to Azure Container Apps from within Visual Studio. We should investigate. For context, the report is a ~500MB layer (containing TorchSharp native libraries + ~16MB of app libraries) took about 28 minutes to upload, consistently.

We should 
* [ ] have tests that cover pushing large layers to a local Docker registry and daemon
* [ ] have test that uses msbuild.exe to perform the publish
* [ ] create another test at baronfel/sdk-container-demo that pushes a large layer to at least one registry and verify that from the CLI there are no problems.
* [ ] investigate the VS scenario, probably using network traffic diagnostics tools like wireshark/fiddler to track requests to the destination registry to make sure they are taking the amount of time we expect

**Comment by vlada-shubina** [comment]
I made comparison test: 
- push to Docker Hub using `Microsfoft.NET.Build.Containers` of default self-contained web app (230 MB) takes 9.5 minutes
- push to Docker Hub using Docker Desktop of same app takes ~15 second

**Comment by baronfel** [comment]
disabling chunked uploads restore the speed for sure. we either need to turn chunked uploads off for ACR, tune the chunk sizes, or do something else to sidestep the problem (parallel chunk upload?)

**Comment by damianh** [comment]
It's also extremely slow pushing to GitLab container registry. Downgrading to 0.4.0 package yielded no improvement.

**Comment by baronfel** [comment]
@damianh if you can use the nightly packages, we've added flags to control if we upload using chunks or not, and if so what the size of the chunks are. A small chunk size is the primary cause of slowness here, so that should help. The variable name for the previews is `SDK_CONTAINER_REGISTRY_CHUNKED_UPLOAD_SIZE_BYTES`, and you can set it to an integral value. I've found that < 5MB works decently-well, ~1MB works almost everywhere. For reference we default to 64kb :D

**Comment by vlada-shubina** [comment]
This was fixed in https://github.com/dotnet/sdk/pull/33336 and https://github.com/dotnet/sdk/pull/33500
