### ISSUE TITLE
ContainerRegistry tag for docker hub does not work

### ISSUE THREAD

**Issue by eliassal** [dotnet/sdk-container-builds#419]
Hi,
Regarding authentication against DockerHub
when trying for example
` dotnet publish --os linux -c Release -p:PublishProfile=DefaultContainer **-p:ContainerImageName=hellodocker-api-modern** -p:ContainerImageTag=1.0.1`

login to docker hub using the 1st option  "registry.hub.docker.com" is not sufficient

The ContainerImageName should contain the **login**/ContainerImageName

So maybe this needs to be indicated in the authentication part of this repo to help anyone having issues

**Comment by baronfel** [comment]
Thanks, this is a good call-out. I've opened #420 to add a note on this. This is a fairly common need, though - for example Github Packages has the same requirement.
