### ISSUE TITLE
.NET containers roadmap

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/sdk-container-builds#428]
This issue represents the list of major investments .NET containers team will focus next. It does not include all the features and bugfixes we will be tackling during this time.

Note that this is an aspirational list of what we hope to get to. Many of these items will require thorough investigation and design, which can result in changes to our plans. We will end up cutting some things and making changes as we go but will try to keep this issue up to date to reflect on our progress and learnings.

Short term plans:
- bug fixing
- better integration to .NET SDK
    - https://github.com/dotnet/sdk-container-builds/issues/370
    - https://github.com/dotnet/sdk-container-builds/issues/402
- including real integration scenarios to CI (https://github.com/dotnet/sdk-container-builds/issues/371)

Long term vision (beyond .NET 8):
- https://github.com/dotnet/sdk-container-builds/issues/87
- https://github.com/dotnet/sdk-container-builds/issues/325
- better integration to Visual Studio and Visual Studio Code
- https://github.com/dotnet/sdk-container-builds/issues/438

Please feel free to give the feedback via reactions or comments.

**Comment by alrz** [comment]
Any plans to remove docker dependency? For this to work with other tools like kaniko we should be able to generate a dockerfile.

**Comment by baronfel** [comment]
Why do you think we have a Docker dependency?

**Comment by alrz** [comment]
Sorry, the docs does mention docker but it seems like that's not true for CI builds (my info was a little outdated on that). Thanks.

**Comment by baronfel** [comment]
No worries! You mentioned kaniko - are you trying to integrate with it for some reason? If so, can you raise a [discussion](https://github.com/dotnet/sdk-container-builds/discussions) where we can talk about it further outside of this issue?
