### ISSUE TITLE
Git gets dirty when publishing

### ISSUE THREAD

**Issue by maxreb** [dotnet/sdk-container-builds#429]
Hey,

I use `MSBuildGitHash` plugin to write the git commit hash in my assembly. When I publish the container I allways get a warning, that the git version is dirty:

> /home/max/.nuget/packages/msbuildgithash/2.0.2/build/MSBuildGitHash.targets(101,5): warning : MSBuildGitHash: the git version is dirty. You should commit all changes before building, or the assembly versions will be inconsistent. [/mnt/c/Users/maxre/source/repos/xxx/XX/YYYY.csproj]

I build with this command in wsl

```console
dotnet publish --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer -p:ContainerImageName=xx/yyyy -p:ContainerImageTag=dev
```

I assume this is because while publishing some files are added/changed or what ever. Is there a way to fix this? Or could you add to the documentation which files those are so one can put them in the `.gitignore` file?

Thanks in advance,
Max

**Comment by baronfel** [comment]
We mostly use the temp directory provided by `Path.GetTempPath()` as the root for all intermediate files generated by this tooling:

* application layer tarballs
* downloaded tarballs for other image layers

Without more information about the state of the repository, why do you think the warning is coming from something the container tools have written? Is the repository dirty at all after a 'normal' `dotnet publish`?

**Comment by maxreb** [comment]
`dotnet publish` had the same issue and so i figured out, that it was another issue (a line feed issue due to different development platforms 🙄) 
thanks and sorry for the inconvenience

**Comment by baronfel** [comment]
No worries, glad you found an answer!
