### ISSUE TITLE
How to push image to Azure Container Registry using Azure Devops service connection?

### ISSUE THREAD

**Issue by danielvan1** [dotnet/sdk-container-builds#436]
I have been looking in [authentication documentation](https://github.com/dotnet/sdk-container-builds/blob/main/docs/RegistryAuthentication.md) and also find other resource. For example this blog post show how it can be achieved with [GitHub Actions](https://devblogs.microsoft.com/dotnet/announcing-builtin-container-support-for-the-dotnet-sdk/). But I have not been able to find documentation or an example how to push images to Azure Container Registry from Azure Pipelines using a service connection.

Can someone tell me if this is possible? If yes, can you point me to some documentation or an example?

**Comment by baronfel** [comment]
Hello @danielvan1 - using Service Connections currently isn't supported with this tooling, we have an open bug tracking this at https://github.com/dotnet/sdk-container-builds/issues/425. The team has just gotten our own Azure resources provisioned for testing, so we'll be looking into what's not working in the near future. I'd expect as part of that resolution we'd have a test or sample that you should be able to use as a reference to make your own scenario work.

**Comment by danielvan1** [comment]
Hi @baronfel
Thank you for the quick answer! :)

**Comment by ggirard07** [comment]
@danielvan1 The easiest way for now I found is to publish the image with this tooling to local registry on the agent (which is the default out of the box when doing `dotnet publish`) and then use the ADO Docker task to actually perform the push-only of the image to the Azure container registry as final step.

**Comment by baronfel** [comment]
I'm going to close this because I believe the core need is tracked in #425. Please track that issue for updates.
