### ISSUE TITLE
Project unload due to missing feature when adding `ContainerBaseImage` to csproj

### ISSUE THREAD

**Issue by ggirard07** [dotnet/sdk-container-builds#437]
As soon as I add the `ContainerBaseImage` to my WebAPI csproj, Visual Studio unloads it and complains about missing feature(s).
I then have a tooltip for installing missing components which starts the Visual Studio Installer to install the ".Net desktop development" Workload, for an 747Mb of additional size.
I currently only have the "ASP.Net and web development" workload installed as it is all I am using and need.

Is it possible to get better insights on which individual(s) component(s) I might actually be missing to use `ContainerBaseImage`, instead of an entire workload?

**Comment by baronfel** [comment]
@vijayrkn do you have any insight into what the different workload components require? Nothing jumps out to me in the implementation we've done that explicitly triggers anything in VS's In-Product Acquisition system.

**Comment by ggirard07** [comment]
I fixed my issue but still do not have an explanation for the missing feature itself.

I was specifying the `ContainerBaseImage` in the `ItemGroup` used for my ports config instead of the `PropertyGroup` 😅 
A colleague tested it on its machine and he got the right error about the invalid parent for the instruction in its csproj.
I still do not understand why my Visual Studio is not returning the same error, but ask for missing feature instead.
