### ISSUE TITLE
dotnet/sdk/8.0.100-preview.4.23260.1/containerize is missing debug symbols

### ISSUE THREAD

**Issue by omajid** [dotnet/sdk-container-builds#440]
### Describe the Bug

.NET 8 Preview 4 introduces a new binary `containerize`. This is missing debug symbols. Running https://pagure.io/dotnet-sig/dotnet8.0/blob/main/f/check-debug-symbols.py against it flags these errors:

```
error: missing .debug_info section in dotnet/sdk/8.0.100-preview.4.23260.1/containerize
error: missing .debug_abbrev section in dotnet/sdk/8.0.100-preview.4.23260.1/containerize
error: missing FILE symbols in dotnet/sdk/8.0.100-preview.4.23260.1/containerize
```

Other files in the just-built SDK, such as the apphost template (`otnet/sdk/8.0.100-preview.4.23260.1/AppHostTemplate/apphost`) have complete debug information.

### Steps to Reproduce

1. Build a .NET 8 Preview 4 SDK.
2. Scan the produced SDK using https://pagure.io/dotnet-sig/dotnet8.0/blob/main/f/check-debug-symbols.py. I used this invocation: `check-debug-symbols.py -v $PATH_TO_EXTRACTED_8_PREVIEW_4_SDK`

**Comment by vlada-shubina** [comment]
The issue appeared more complicated. After excluding containerize, the packaging stopped working as it relies on its artifacts for other deliverables. We need to change the way packaging works to allow that.

**Comment by baronfel** [comment]
I just merged the linked PR, so when that flows to dotnet/sdk's main branch we should be all good to go. I'd expect preview6 nightlies to start passing @omajid's tests now.
