### ISSUE TITLE
Emit a warning when given a ContainerBaseImage that doesn't specify a registry

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk-container-builds#443]
Like the `docker` cli, the tooling will resolve an unqualified image name from the `docker.io` registry.

```
internal const string DefaultRegistry = "docker.io";
```

The default configuration of the `podman` cli requires any image that is pulled to be fully qualified.

@baronfel do you prefer to keep the behavior as-is, or would you be ok with users having to prepend the `ContainerBaseImage` with `docker.io/` if they host them on Docker Hub?

**Comment by baronfel** [comment]
I would prefer to keep the 'it just works' nature here if possible - so someone pulling from Docker Hub for a library image could use that image transparently regardless of container engine they're pushing to locally.

Is that what you're asking?

**Comment by tmds** [comment]
My question is about what the sdk tooling considers the image source when the registry is not specified.

I think the current behavior is to pull it from `DefaultRegistry` (which is `docker.io`).

That `docker` cli uses `docker.io` make sense: they are both provided by Docker Inc.

Rather than including a default of `docker.io`, we could require users to specify the registry explicitly.

That is the behavior of `podman`:
```
$ podman run something
? Please select an image: 
  ▸ registry.fedoraproject.org/something:latest
    registry.access.redhat.com/something:latest
    docker.io/library/something:latest
    quay.io/something:latest
```
The list of suggestions made to the user here comes from the config in `/etc/containers/registries.conf` (which each distro can customize). Unlike the `docker` cli, it doesn't default to `docker.io` for short names.

That said, I'm now trying to see when/how the tooling uses the `DefaultRegistry` but I haven't found a value of `<ContainerBaseImage>` that successfully pulls an image from the implicit `DefaultRegistry`. It seems to be broken.

**Comment by baronfel** [comment]
Ah, I see. I think the 'best' thing to do here from a UX perspective (since the `docker` CLI is what I think the majority of users are expecting) would be to auto-expand using `docker.io` as the base registry, _but_ log a warning (or message) when this occurs. We should encourage the use of fully-qualified image names as the base images as much as possible, but we should also be able to be flexible in line with most folks' expectations.

**Comment by tmds** [comment]
Got it. I've updated the title accordingly, and created https://github.com/dotnet/sdk-container-builds/issues/444 and https://github.com/dotnet/sdk-container-builds/issues/445 for the issues with `docker.io`/`DefaultRegistry`.
