### ISSUE TITLE
Publish to yandex container registry

### ISSUE THREAD

**Issue by leotsarev** [dotnet/sdk-container-builds#455]
https://cloud.yandex.com/en/docs/container-registry/operations/docker-image/docker-image-push

**Comment by baronfel** [comment]
Hello @leotsarev I don't know of any reason why we can't work with a Yandex registry, but I have not been able to test because I cannot create a billing account from my country.  If you are able to test the tooling with Yandex and provide feedback either way, we would document that.

**Comment by leotsarev** [comment]
@baronfel it isn't working, actually.
I'm passing 	
```csproj
<ContainerRuntimeIdentifier>linux-x64</ContainerRuntimeIdentifier>
<ContainerRegistry>cr.yandex/crp3fr717nr1rn78qeij/</ContainerRegistry>
```
(tried both `cr.yandex/crp3fr717nr1rn78qeij/` and `cr.yandex/crp3fr717nr1rn78qeij`)

Seems that `ContainerHelpers.IsValidRegistry` doesn't allow paths in registry name. 

I could provide your with test registry, if you want. You have to register yandex account and I'll give you access. Put email for this account here or email me to leo@leotsarev.ru or ping using telegram @leotsarev

**Comment by leotsarev** [comment]
>I cannot create a billing account from my country.

My friends from abroad says it should be possible. Just tested and it's possible i.e. from Serbia (so it's possible from "international" side of sanctions wall).

**Comment by baronfel** [comment]
@leotsarev ah, for registries with paths, you use the 'base' registry name for ContainerRegistry, and you prepend the path portion to ContainerImageName. Google Cloud does the same thing, here's an example: https://github.com/baronfel/sdk-container-demo/blob/main/Properties/PublishProfiles/gcp.pubxml

**Comment by leotsarev** [comment]
It works now (after bump from 7.0.302 to 7.0.401)

**Comment by baronfel** [comment]
Great to hear it @leotsarev!
