### ISSUE TITLE
Chunked upload doesn't work for public AWS ECR

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/sdk-container-builds#472]
Follow up: https://github.com/dotnet/sdk-container-builds/issues/424

Steps to repro:
- set  to force chunked upload
- prepare project to publish (dotnet new webapi)
- login to public AWS ECR
- configure publish profile to push to public AWS ECR
- `dotnet publish --os linux --arch x64 --configuration Release -p:PublishProfile=<your profile>.pubxml`

Error occurs:
`error CONTAINER1013: Failed to push to the output registry: CONTAINER1001: Failed to upload blob using PUT https://public.ecr.aws/v2/r4z9b1c4/sdk-containers-test/blobs/uploads/38a481f9-7788-420b-8690-d8ac7531
a60e?&digest=sha256%3A9d21b12d5fab9ab82969054d72411ce627c209257df64b6057016c981e163c30; received status code 'BadRequest'. `

Binlog trace:
<img width="687" alt="image" src="https://github.com/dotnet/sdk-container-builds/assets/56045248/92b640f2-1ac3-4322-b4dc-e36c37db4839">

```
Last request URI: https://public.ecr.aws/v2/r4z9b1c4/sdk-containers-test/blobs/uploads/38a481f9-7788-420b-8690-d8ac7531a60e?&digest=sha256%3A9d21b12d5fab9ab82969054d72411ce627c209257df64b6057016c981e163c30
Status code: BadRequest
Response headers:
Date: Tue, 04 Jul 2023 13:34:41 GMT
Connection: keep-alive
Docker-Distribution-Api-Version: registry/2.0

Response content: {"errors":[{"code":"BLOB_UPLOAD_INVALID","message":"None of the provided layer digests match the calculated layer digest"}]}
```

Chunked upload works: 
- private AWS ECR
- ACR (however slow)

This issue is low priority:
- occurs only when atomic upload fails
- public AWS ECR is relatively low use

**Comment by baronfel** [comment]
We have AWS-specific quirks that are working now.
