### ISSUE TITLE
Missing property to set healthcheck for container

### ISSUE THREAD

**Issue by Dakraid** [dotnet/sdk-container-builds#476]
Greetings,
within a project we have encountered a difficulty with setting the healthcheck for the images generated by the dotnet publish targeting containers.

The healtcheck is a standard instruction for Dockerfile as described here: https://docs.docker.com/engine/reference/builder/#healthcheck

But without building a custom image to be used as base, there doesn't seem to be a way to set this up right now. This issue has been raised before at [316](https://github.com/dotnet/sdk-container-builds/issues/316) and provides a lot more in-depth information.

Thank you and have a nice day.

**Comment by Kralizek** [comment]
I'm having the same issue. It feels bad to go back to Dockerfiles just for this.

**Comment by baronfel** [comment]
Closing for similar reasons to #316 - We're not going to lean into healthcheck support in the SDK container tooling itself because this extension is Docker-only and has no support in OCI images, which the container world is moving towards.
