### ISSUE TITLE
Create a ContainerPort item for the ASPNETCORE_URLs environment variables if set

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#478]
ASP.NET has a few environment variables that control which ports/urls are used for hosting the application

* ASPNETCORE_URLS
* ASPNETCORE_HTTP_PORTS
* ASPNETCORE_HTTPS_PORTS

We should check for these in the environment block of an application, and attempt to define `ExposedPort` metadata for any ports found there. `ASPNETCORE_HTTP_PORTS` and `ASPNETCORE_HTTPS_PORTS` have a simple syntax of semicolon-delimited port numbers, but `ASPNETCORE_URLS` has a format of semicolon-delimited `{scheme}://{address}:{port}` items, where `address` is one of:
* `localhost`
* an IP address
* `*`

Creating these ports allows other tooling like the VSCode Docker tooling to automatically detect and expose ports when users run our containers.

**Comment by danegsta** [comment]
@baronfel as a heads up, this is the parser from the aspnetcore project for parsing the entries in ASPNETCORE_URLS: https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http/src/BindingAddress.cs

**Comment by baronfel** [comment]
Yeah, this is going to be A Thing :tm:

**Comment by danegsta** [comment]
@baronfel the main complication comes from the fact that the URLs they use aren't always real valid URLs; they use special characters to represent binding to any address (usually noted with `0.0.0.0` elsewhere), so `http://+:80;https://+:443` is a totally valid ASPNETCORE_URLS value. You can probably get away with simple split on ';' plus a simple regex to match `<protocol>://<host like value>:<port>` and call it a day.
