### ISSUE TITLE
Provide auth mechanism that doesn't rely on ~/.docker/config.json

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk-container-builds#484]
I want to build container images within Docker, using the following pattern:

```bash
docker run --rm -it -v $(pwd):/source -v /home/rich/.docker:/root/.docker -w /source mcr.microsoft.com/dotnet/aot-sdk dotnet publish /p:PublishProfile=DefaultContainer /p:ContainerRegistry=maplesugar.azurecr.io
```

This works great on Linux, where `~/.docker/config.json` contains unencrypted passwords. It doesn't work on macOS or Windows where the passwords are stored in an OS-provided cred store.

This scenario is only somewhat compelling for CoreCLR apps. It is very compelling for native AOT apps, which require additional pre-reqs be installed that don't come with the .NET SDK.

Note that I'm using `dotnet/aot-sdk` above. It includes the Native AOT pre-reqs. It's so new that it doesn't yet exist. We intend to have it available for .NET 8 GA.

This is very similar to wanting to be able to build container images on CI w/o installing Docker. /cc @normj

This container build solution could be a lot more powerful if we could unhook it from the Docker client mechanisms.

Something like the following would be great.

```bash
docker run --rm -it -v $(pwd):/source -v /home/rich/.docker:/root/.docker -w /source mcr.microsoft.com/dotnet/sdk dotnet publish /p:PublishProfile=DefaultContainer /p:ContainerRegistry=maplesugar.azurecr.io /p:ContainerRegistryUser=richlander /p:ContainerRegistryPassword=$RegistryPassword
```

**Comment by baronfel** [comment]
I'm confused by the comment about credential stores - we do support those on all platforms via the DockerCredsProvider library.

We also explicitly chose not to support username/password because those properties appear in binlogs, so reduce the ability to diagnose. We'd possibly need to wait for @JanKrivanek's secrets feature before adding?

**Comment by richlander** [comment]
Yes, volume mounted build.

A secrets features sounds good.

**Comment by richlander** [comment]
I wrote a little tool that may be good enough.

```csharp
using System.Buffers.Text;
using System.Text;

if (!Console.IsInputRedirected)
{
    return;
}

var creds = Console.In.ReadLine();

if (string.IsNullOrEmpty(creds))
{
    return;
}

var authBytes = UTF8Encoding.UTF8.GetBytes(creds);
var auth = System.Convert.ToBase64String(authBytes);

var json = $$"""
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "{{auth}}"
		}
	}
}
""";

Console.WriteLine(json);
```

Usage pattern is like this:

```bash
$ cat secret.txt | ./bin/Debug/net8.0/configjson > ~/myconfigjson/config.json
```

Secret is: username:password

Then:

```bash
docker run --rm -it -v $(pwd):/source -v /Users/rich/myconfigjson:/root/.docker -w /source mcr.microsoft.com/dotnet/sdk:8.0-preview dotnet publish /p:PublishProfile=DefaultContainer /p:ContainerRegistry=docker.io /p:ContainerRepository=richlander/bar
```

This isn't currently working, but I suspect it will once Preview 7 is out. I tried with `nightly` but that didn't work either. I'll try again later.

**Comment by tmds** [comment]
You can pass the username and password using the `SDK_CONTAINER_REGISTRY_UNAME` and `SDK_CONTAINER_REGISTRY_PWORD` envvars.

And with preview7, if you have a custom json auth file file, you can set the `REGISTRY_AUTH_FILE` envvar to its path.

**Comment by richlander** [comment]
Still having trouble. Same error I was getting with volume mounting my `config.json` file. This is P7. Do I need a newer build?

```bash
docker run --rm -it -v $(pwd):/source -w /source mcr.microsoft.com/dotnet/nightly/sdk:8.0-preview dotnet publish /p:PublishProfile=DefaultContainer /p:ContainerRegistry=docker.io /p:ContainerRepository=richlander/bar /p:SDK_CONTAINER_REGISTRY_UNAME=richlander /p:SDK_CONTAINER_REGISTRY_PWORD=_elided_
MSBuild version 17.8.0-preview-23367-03+0ff2a83e9 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/usr/share/dotnet/sdk/8.0.100-preview.7.23376.3/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(314,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/source/aspnetapp.csproj]
  aspnetapp -> /source/bin/Release/net8.0/aspnetapp.dll
  aspnetapp -> /source/bin/Release/net8.0/publish/
/usr/share/dotnet/sdk/8.0.100-preview.7.23376.3/Containers/build/Microsoft.NET.Build.Containers.targets(201,5): error MSB4018: The "CreateNewImage" task failed unexpectedly. [/source/aspnetapp.csproj]
/usr/share/dotnet/sdk/8.0.100-preview.7.23376.3/Containers/build/Microsoft.NET.Build.Containers.targets(201,5): error MSB4018: System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found). [/source/aspnetapp.csproj]
/usr/share/dotnet/sdk/8.0.100-preview.7.23376.3/Containers/build/Microsoft.NET.Build.Containers.targets(201,5): error MSB4018:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() [/source/aspnetapp.csproj]
/usr/share/dotnet/sdk/8.0.100-preview.7.23376.3/Containers/build/Microsoft.NET.Build.Containers.targets(201,5): error MSB4018:    at Microsoft.NET.Build.Containers.DefaultManifestOperations.GetAsync(String repositoryName, String reference, CancellationToken cancellationToken) in /_/src/Containers/Microsoft.NET.Build.Containers/Registry/DefaultManifestOperations.cs:line 30 [/source/aspnetapp.csproj]
/usr/share/dotnet/sdk/8.0.100-preview.7.23376.3/Containers/build/Microsoft.NET.Build.Containers.targets(201,5): error MSB4018:    at Microsoft.NET.Build.Containers.Registry.GetImageManifestAsync(String repositoryName, String reference, String runtimeIdentifier, String runtimeIdentifierGraphPath, CancellationToken cancellationToken) in /_/src/Containers/Microsoft.NET.Build.Containers/Registry/Registry.cs:line 110 [/source/aspnetapp.csproj]
/usr/share/dotnet/sdk/8.0.100-preview.7.23376.3/Containers/build/Microsoft.NET.Build.Containers.targets(201,5): error MSB4018:    at Microsoft.NET.Build.Containers.Tasks.CreateNewImage.ExecuteAsync(CancellationToken cancellationToken) in /_/src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs:line 61 [/source/aspnetapp.csproj]
/usr/share/dotnet/sdk/8.0.100-preview.7.23376.3/Containers/build/Microsoft.NET.Build.Containers.targets(201,5): error MSB4018:    at Microsoft.NET.Build.Containers.Tasks.CreateNewImage.Execute() in /_/src/Containers/Microsoft.NET.Build.Containers/Tasks/CreateNewImage.cs:line 35 [/source/aspnetapp.csproj]
/usr/share/dotnet/sdk/8.0.100-preview.7.23376.3/Containers/build/Microsoft.NET.Build.Containers.targets(201,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/source/aspnetapp.csproj]
/usr/share/dotnet/sdk/8.0.100-preview.7.23376.3/Containers/build/Microsoft.NET.Build.Containers.targets(201,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/source/aspnetapp.csproj]
```

**Comment by tmds** [comment]
> Response status code does not indicate success: 404 (Not Found). [/source/aspnetapp.csproj]

This may mean the SDK doesn't find the base image. Try setting `ContainerBaseImage` explicitly.

**Comment by richlander** [comment]
Getting farther. That worked if I volume mount my `config.json` file. I get the following error if I set those those two creds ENVs (same as in the last comment I posted).

```
/usr/share/dotnet/sdk/8.0.100-preview.7.23376.3/Containers/build/Microsoft.NET.Build.Containers.targets(201,5): error CONTAINER1013: Failed to push to the output registry: CONTAINER1008: Failed retrieving credentials for "docker.io": Docker config file doesn't exist. [/source/aspnetapp.csproj]
```

**Comment by tmds** [comment]
> /p:SDK_CONTAINER_REGISTRY_UNAME=richlander /p:SDK_CONTAINER_REGISTRY_PWORD=_elided_

You can't set these using `/p:` as they are not msbuild properties. You need to use `-e` to set them as arguments.

The error message should then also disappear because when these envvars are set, the config file is no longer used.

**Comment by richlander** [comment]
Got it. I didn't realize that these needed to be set as ENVs. The casing should have been the clue!

That worked. Thanks!

All of this satisfies my needs. We'll need to ensure all of this is doc'd. I appreciate the flexibility these knobs offer.

**Comment by baronfel** [comment]
We've not really talked about those environment variables because they were added to make it easier for VS to send credentials to us in a way that doesn't end up in binlogs. It does make sense to document to enable this use case, though.

One downside to expanding the usage of these environment variables is they won't work if we add in the capability to push to multiple authenticated registries in one operation. I'm not in favor of doing this, but at least one user has asked for it.

**Comment by normj** [comment]
Came to the party late but the new environment variables look really useful and should be documented.

**Comment by richlander** [comment]
The auth file should and can already be used to push to multiple registries. The current surface area seems sufficient.

**Comment by cphillips83** [comment]
> We've not really talked about those environment variables because they were added to make it easier for VS to send credentials to us in a way that doesn't end up in binlogs. It does make sense to document to enable this use case, though.
> 
> One downside to expanding the usage of these environment variables is they won't work if we add in the capability to push to multiple authenticated registries in one operation. I'm not in favor of doing this, but at least one user has asked for it.


Not to necro this, but lost a lot of hours to a vague error of something like `Can't auth due to missing docker config file` and no that doesn't mean create a `.docker/config.json` is means pass these variables in that aren't documented!

EDIT: To clarify, I was doing a simple task of using a different base image from docker hub, something that I'm sure a lot of people will try to do with the simplistic `dotnet publish` command that doesn't require you to use a `Dockerfile`
