### ISSUE TITLE
Support RuntimeFrameworkVersion to infer image tag version

### ISSUE THREAD

**Issue by scrocquesel-ml150** [dotnet/sdk-container-builds#488]
Actually, the image tag is build from the `TargetFramework` and use stable tag.

```xml
 <TargetFramework>net7.0</TargetFramework>
 <!--  with only TargetFramework
 <ContainerBaseImage>mcr.microsoft.com/dotnet/runtime:7.0</ContainerBaseImage>
-->
<RuntimeFrameworkVersion>7.0.9</RuntimeFrameworkVersion>
 <!-- 
<ContainerBaseImage>mcr.microsoft.com/dotnet/runtime:7.0.9</ContainerBaseImage>
 -->
```

Something like

```xml
<Target Name="ComputeContainerBaseImageTagOverride" Returns="$(_ContainerBaseImageTag)"
    DependsOnTargets="_ComputeContainerBaseImageTag" BeforeTargets="ComputeContainerBaseImage">
    <PropertyGroup>
      <_ContainerBaseImageTag Condition="'$(RuntimeFrameworkVersion)' != ''">$(RuntimeFrameworkVersion)</_ContainerBaseImageTag>
    </PropertyGroup>
  </Target>
```

**Comment by baronfel** [comment]
That's still a useful start - we can parse the FrameworkRuntimeVersion as a SemVer and only keep the first 'preview' segment + iteration. That's still a more useful/general rule than we're currently using.

**Comment by richlander** [comment]
`RuntimeFrameworkVersion` is a (really) bad idea for this. Another (container-specific) property should be used.

Partial (but sufficient) context: https://github.com/dotnet/runtime/issues/90096

@elinor-fung

**Comment by baronfel** [comment]
Alright, we can back off of this approach then. The current approach will possibly float the user to a newer runtime than they may have manually specified (because we're using the major-minor version of the tag, but we generally try to be very compatible across those versions so it _should_ be safe.

**Comment by richlander** [comment]
I have no issue with a `ContainerPatchVersion` tag (or similar). It's just that the use of `RuntimeFrameworkVersion`, which very much does other stuff (good and bad) in addition to it being useful for inference.

**Comment by scrocquesel** [comment]
> Alright, we can back off of this approach then. The current approach will possibly float the user to a newer runtime than they may have manually specified (because we're using the major-minor version of the tag, but we generally try to be very compatible across those versions so it _should_ be safe.

My use case is to be able to use [Renovate](https://github.com/renovatebot/renovate/issues/18434) to have a framework version that is manageable and predictable and being able to deduce the corresponding supported runtime image.

**Comment by scrocquesel** [comment]
> `RuntimeFrameworkVersion` is a (really) bad idea for this. Another (container-specific) property should be used.
> 
> Partial (but sufficient) context: [dotnet/runtime#90096](https://github.com/dotnet/runtime/issues/90096)
> 
> @elinor-fung

Does it means that we can actually build the application in an image with the same runtime version but it will not work ?

**Comment by richlander** [comment]
The issue is that `RuntimeFrameworkVersion` (as the linked issue suggests) only affects the base runtime and has no effect on other frameworks.

It's a supported feature, however, has very narrow utility, and we do not want to encourage its broad use (which this would do).

**Comment by scrocquesel-ml150** [comment]
@baronfel I guess this one can be closed in favor of https://github.com/dotnet/sdk-container-builds/issues/488.
I assume we can just track digests of say `mcr.microsoft.com/dotnet/aspnet:8.0` to stay up-to-date .
