### ISSUE TITLE
with own base image api is not starting anymore

### ISSUE THREAD

**Issue by LennartKleymann** [dotnet/sdk-container-builds#498]
If i publish using this command: 
`dotnet publish -c Release -p:ContainerBaseImage=registry-1.docker.io/kleymannl/dotnet-libfontconfig1:latest -p:ContainerImageName=replaced/replaced -p:RuntimeIdentifier=linux-x64`

the container is not starting anymore and I get following error message: 
`replaced.path: no such file or directory`

My base image looks like this: 
```
FROM mcr.microsoft.com/dotnet/runtime-deps:7.0
RUN apt-get update
RUN apt-get install -y libfontconfig1
```

**Comment by LennartKleymann** [comment]
BinLog is a little bit complicated, because it contains sensitive data for me. 
Can I share it to you privately? @baronfel

**Comment by baronfel** [comment]
Sure! Create a new developer community ticket [here](https://developercommunity.visualstudio.com/dotnet/report), and once you've created the ticket you can upload the binlog privately to that site. Then you can comment back here with the link to the ticket you just created and I'll be able to securely access the binlog.

**Comment by LennartKleymann** [comment]
Okay thanks. I attached the binlog to a private comment for microsoft only. 
https://developercommunity.visualstudio.com/t/sdk-container-builds:-with-own-base-imag/10461318

**Comment by baronfel** [comment]
@LennartKleymann can you take a look at [this comment](https://github.com/dotnet/sdk-container-builds/issues/499#issuecomment-1712007764)? This is what I'm hoping to get into .NET 8 that would identify and force you to handle this error case.

**Comment by LennartKleymann** [comment]
@baronfel Hey, sorry for the late response.
With building my base image on the correct plattform my publsih of my API works.

I think that the comment you link is really good to prevent confusion, thank you really much.
