### ISSUE TITLE
The tooling can't push to Sonatype Nexus 3

### ISSUE THREAD

**Issue by schmitch** [dotnet/sdk-container-builds#527]
### Describe the bug
if seombody wants to use a `ContainerBaseImage` that is not inside a public repository the `LANG=en dotnet publish -c Release -p ContainerImageTags="ef-test" /t:PublishContainer` command would fail

### To Reproduce
1. docker login docker.envisia.io # we use `nexus sonatype 3`
2. `LANG=en dotnet publish -c Release -p ContainerBaseImage=docker.envisia.io/envisia/dotnet/runtime-german:8.0  -p ContainerImageTags="ef-test" /t:PublishContainer`

### Exceptions (if any)
```
/usr/local/share/dotnet/sdk/8.0.100/Containers/build/Microsoft.NET.Build.Containers.targets(202,5): error CONTAINER1016: Unable to access the repository 'envisia/dotnet/runtime-german' in the registry 'docker.envisia.io'. Please confirm your credentials are correct and that you have access to this repository and registry. [HIDDEN/dotnet/Envisia.Erp.Web/Envisia.Erp.Web.csproj]
```

### Further technical details
```
dotnet --info
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.71b9f198

Laufzeitumgebung:
 OS Name:     Mac OS X
 OS Version:  14.1
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100/

Installierte .NET-Workloads:
 Workload version: 8.0.100-manifests.71b9f198
 [aspire]
   Installationsquelle: SDK 8.0.100
   Manifestversion:    8.0.0-preview.1.23557.2/8.0.100
   Manifestpfad:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.aspire/8.0.0-preview.1.23557.2/WorkloadManifest.json
   Installationstyp:        FileBased


Host:
  Version:      8.0.0
  Architecture: arm64
  Commit:       5535e31a71

.NET SDKs installed:
  6.0.410 [/usr/local/share/dotnet/sdk]
  7.0.403 [/usr/local/share/dotnet/sdk]
  8.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:

  Microsoft.AspNetCore.App 6.0.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  DOTNET_ROOT       [/usr/local/share/dotnet]

global.json file:
  HIDDEN/dotnet/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by schmitch** [comment]
@baronfel I can generate a flow file with [mitmproxy](https://mitmproxy.org/) but I'm not sure if it is helpful.

the only thing that is happening is the following:

```
HEAD /v2/erp/web-dotnet/blobs/sha256:a5d27c632fdcf7a46101d34ed14b06ed6efe90a5086fa615619564ae7bdfd45d HTTP/1.1
Host: docker.envisia.io
User-Agent: .NET Container Library v8.0.100-rtm.23551.6+e9d13cbe7e8c1d52ce276a8655f52a87e1017c46
content-length: 0



HTTP/1.1 401 Unauthorized
Date: Mon, 27 Nov 2023 17:20:09 GMT
Content-Type: application/json
Content-Length: 0
Connection: keep-alive
X-Content-Type-Options: nosniff
Content-Security-Policy: sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation
X-XSS-Protection: 1; mode=block
WWW-Authenticate: BASIC realm="Sonatype Nexus Repository Manager"
Accept-Ranges: bytes
Docker-Distribution-Api-Version: registry/2.0
Strict-Transport-Security: max-age=15724800; includeSubDomains
```

multiple HEAD calls without any authencation data at all. it responds with a `WWW-Authenticate: BASIC realm="Sonatype Nexus Repository Manager"` but no further request is done.

**Comment by baronfel** [comment]
I think this may be a bug in our authentication implementation. We're checking for WWW-Authenticate schemes case-sensitively, but per the spec schemes should be case-insensitive. If you have any control, can you rewrite the response from Nexus to be `WWW-Authenticate: Basic realm="Sonatype Nexus Repository Manager"` instead of `BASIC`?

**Comment by schmitch** [comment]
sadly I think that is at least not an option in nexus directly. besides that there is a settings page to reorder the realms which should change the response of www-authenticate, but that did not work on my side.
I can try to overwrite it in nginx tomorrow.

**Comment by baronfel** [comment]
@schmitch here's a slightly easier thing to try. I've attached a nuget package of the SDK containers tech - you can drop this in a folder and use that folder as a nuget source via `dotnet nuget add source`, then add a `PackageReference` to this package and version. You'll need to remove the `.zip` for NuGet to recognize the package too.

Once you do this you should be able to publish your app and if this was in fact the problem you should see auth handshakes occur.

[Microsoft.NET.Build.Containers.8.0.200-dev.nupkg.zip](https://github.com/dotnet/sdk-container-builds/files/13480515/Microsoft.NET.Build.Containers.8.0.200-dev.nupkg.zip)

**Comment by schmitch** [comment]
looks like it still did nothing, it only did a HEAD request:

```
HEAD /v2/erp/web-dotnet/blobs/sha256:2c6d21737d8318aa15c4cc838475029a5efc36c0429e3d8da80d97d0b96d9aaf HTTP/1.1
Host: docker.envisia.io
User-Agent: .NET Container Library v8.0.200-dev
content-length: 0



HTTP/1.1 401 Unauthorized
Date: Tue, 28 Nov 2023 08:21:40 GMT
Content-Type: application/json
Content-Length: 0
Connection: keep-alive
X-Content-Type-Options: nosniff
Content-Security-Policy: sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation
X-XSS-Protection: 1; mode=block
WWW-Authenticate: BASIC realm="Sonatype Nexus Repository Manager"
Accept-Ranges: bytes
Docker-Distribution-Api-Version: registry/2.0
Strict-Transport-Security: max-age=15724800; includeSubDomains

```

**Comment by schmitch** [comment]
actually the problem was the `Basic`auth header, but on more occurances:

[diff.txt](https://github.com/dotnet/sdk-container-builds/files/13485786/diff.txt)

this was the diff that worked for my (don't mind the logs, it helped me understand it!)

**Comment by baronfel** [comment]
Oh awesome - thanks for that validation! I'll adopt your changes on the PR shortly. Kudos for cloning the SDK and building it yourself :)

**Comment by baronfel** [comment]
Ok, it looks like I just missed one other place where we were doing string matching instead of insensitive comparisons. I've updated that PR with the changes if you'd like to review/verify the behavior.

**Comment by schmitch** [comment]
everything looks working now.

the baseimage was authenticated as well, sadly my base image is only an oci v1 container:
```
/usr/local/share/dotnet/sdk/8.0.100/Containers/build/Microsoft.NET.Build.Containers.targets(202,5): error MSB4018: System.NotImplementedException: CONTAINER2003: The manifest for envisia/dotnet/runtime-german:8.0 from registry https://docker.envisia.io/ was an unknown type: application/vnd.oci.image.index.v1+json. Please raise an issue at https://github.com/dotnet/sdk-container-builds/issues with this message. [/Users/schmitch/projects/envisia/erp/loki/dotnet/Envisia.Erp.Web/Envisia.Erp.Web.csproj]
```
but thats a problem that I can easily fix on our side probably some `docker buildx` config changes or basically a problem with our docker build that uses `application/vnd.oci.image.index.v1+json` instead of `application/vnd.docker.distribution.manifest.list.v2+json`

**Comment by baronfel** [comment]
@schmitch did you choose the `OCI` index specifically with `docker buildx`? Or was it a default or something? If it's a default that might bump up the priority of implementing support for OCI indexes.

**Comment by schmitch** [comment]
@baronfel no we just use `docker buildx bake -f docker-bake.hcl -f env8.hcl` to cross compile images for different arch's we basically base our images from `mcr.microsoft.com/dotnet/aspnet:8.0` but we need the german locale and timezone (sadly, we didn't do a good job yet when it comes to timezones and the local provider and it's a long road to get rid of that...) and also we need to add ca-certificates and other stuff to the container. so basically we just add stuff and to "cross build" that we use `docker buildx bake` with the following target:

```
target "runtime-dotnet-german" {
    inherits = ["runtime-dotnet-base"]
  dockerfile = "runtime-dotnet/Dockerfile.german"
  tags = [
    "docker.envisia.io/envisia/dotnet/runtime-german:${DOTNET_VERSION}"
  ]
}
```
so nothing special, I do not even now if its possible to set `oci-mediatypes` with `bake`

**Comment by schmitch** [comment]
@baronfel sadly there are no news to this, but btw. I found: https://github.com/opencontainers/image-spec/blob/main/image-index.md which is the opencontainers spec which says that "image consumers SHOULD" support the `application/vnd.oci.image.index.v1+json` media type, it's probably an easy fix, since it's closely related to `application/vnd.docker.distribution.manifest.list.v2+json`

**Comment by Danielku15** [comment]
Unfortunately I also just ran into this problem. In my case JFrog Artifactory provides OCI images (proxying to docker hub).

I already had once created changes for: 

1. Writing OCI container images
2. Reading OCI container images from disk and push them to a registry. 

https://github.com/dotnet/sdk/pull/35204

Not sure if this might help in handling the flow of using OCI base images as inputs. Generally the formats are a bit different in how they organize the blobs and layers. Funnily I think the OCI format is closer to the Docker API than the Docker Format itself.

**Comment by Danielku15** [comment]
@baronfel Does it make sense to create a dedicated issue for the OCI base image support? I have the feeling the discussion in this issue is a bit mixed. The original problem of pushing to Nexus seems to be fixed with the auth handling. 

I might be willing to implement the OCI pull as it is in our interest to have this in the SDK.

**Comment by baronfel** [comment]
We merged a PR to support reading this format, and are working on multi-arch publishing support to handle writing Image Indexes as well.
