### ISSUE TITLE
Container registries that doesn't support OCI Container format

### ISSUE THREAD

**Issue by justinyoo** [dotnet/sdk-container-builds#535]
Hi, Team.

I know that .NET SDK Container Build only supports OCI Container image format. But some container registry service providers don't support the OCI Container format like NHN Cloud and NCP in Korea.

I understand that it's up to them whether to support the OCI Container format, but do we have a long-term roadmap to support another format over OCI Container?

![image](https://github.com/dotnet/sdk-container-builds/assets/1538528/bfb9702c-cacb-4f89-b801-72c4da1f4345)

**Comment by baronfel** [comment]
After some debugging we discovered a few things:

* This tooling supports both docker image manifests and OCI image manifests - whatever the source registry gives us we forward along to the target registry
* The NHN Cloud's registry is based on Harbor registry
* .NET SDK 8.0.200 contains a fix to this tooling to support Harbor - specifically removing cookies that were triggering CSRF tokens

As a result we can close this and look forward to 8.0.200 to unblock this scenario!

**Comment by gonais** [comment]
NHN Cloud has deployed NCR, which supports Helm Chart and OCI Artifact, starting in August 2023.

Please refer to the link below. :)

https://docs.nhncloud.com/en/Container/NCR/en/user-guide/#use-helm-chart
