### ISSUE TITLE
Provide a way to adjust the httpclient timeout for layer pushes

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#543]
Users aren't always in control of their network - we should provide some way for them to override the default .NET timeout for uploads (100s). This pops up in a few places, like https://github.com/Azure/azure-dev/discussions/3212.

Thoughts:
* since the user can cancel the operation at any time, should we just set an infinite timeout? If we do, we will likely need to adapt all existing callsites for the small operations to have short timeouts to prevent hangs. The Timeout in the HttpClient is used to create a linked cancellationToken that cancels after that duration, so we can orchestrate the same here - or simply use the new `WaitAsync(TimeSpan)` methods on `Task<T>` to make that super clear.
  * Note that if we use the generic `WaitAsync`, those throw `TimeoutException`s with little detail, so we should handle them and make them say something useful.

cc @rainersigwald @MichalPavlik

**Comment by BartNetJS** [comment]
got the same issue, see https://github.com/Azure/azure-dev/issues/3225#top

**Comment by baronfel** [comment]
This also bit @mitchdenny hard today.

**Comment by baronfel** [comment]
Customers are hitting this repeatedly on the linked issue. We may need to bump priority + backport to 8.0.200 since Aspire is using that feature branch.

cc @MichalPavlik / @rokonec / @rainersigwald

**Comment by tmds** [comment]
I wonder if the issue isn't caused by the SDK not doing chunked uploads, see https://github.com/Azure/azure-dev/discussions/3212#discussioncomment-8553439.

**Comment by baronfel** [comment]
We've got a hotfix in for 8.0.200 servicing and 8.0.300, but we should have some more usable knob. Moving this to the next milestone as a result.

**Comment by DamianEdwards** [comment]
@baronfel is a fix for this in 8.0.1xx?

**Comment by baronfel** [comment]
No, I'm not sure why I didn't backport that far originally. Folks using 1xx can use the nuget packages for a workaround now, however.

**Comment by baronfel** [comment]
I kicked a backport off that I can get servicing approval for over email.

**Comment by baronfel** [comment]
Backport is https://github.com/dotnet/sdk/pull/41294

**Comment by baronfel** [comment]
The knob seems to be usable enough for users so far. We'll close this and reopen if there is evidence of further need.
