### ISSUE TITLE
Add option to specify registry url from cli

### ISSUE THREAD

**Issue by atrakic** [dotnet/sdk-container-builds#550]
After authentication to ACR, there should be a option to push to ACR without editing Cproj properties. 
Otherwise, please provide documentation how to create and use custom profile `dotnet publish -p:PublishProfile=MyAcr`.

**Comment by dviry** [comment]
Have you tried using /p:ContainerRegistry=xxx ? Seems to work fine for me...

**Comment by baronfel** [comment]
Publish Profiles are just collections of properties, so if you'd like to use a custom Profile you can set any project properties that you like. You can see some examples of custom Publish Profiles (and how to use them) in my demos repo here: https://github.com/baronfel/sdk-container-demo/tree/main/src/sdk-container-demo/Properties/PublishProfiles
