### ISSUE TITLE
Container inferencing for AOT can move to stable repo

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk-container-builds#555]
For container publishing with `PublishAot` (for a .NET 8 app), I see:

```bash
$ dotnet publish /t:PublishContainer
MSBuild version 17.9.4+90725d08d for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  hello-dotnet -> /home/rich/hello-dotnet/bin/Release/net8.0/linux-x64/hello-dotnet.dll
  Generating native code
  hello-dotnet -> /home/rich/hello-dotnet/bin/Release/net8.0/linux-x64/publish/
  Building image 'hello-chiseled-aot' with tags 'latest' on top of base image 'mcr.microsoft.com/dotnet/nightly/runtime-deps:8.0-jammy-chiseled-extra'.
  Pushed image 'hello-chiseled-aot:latest' to local registry via 'docker'.
```

In the "use ICU" case, the following image can be used: `mcr.microsoft.com/dotnet/runtime-deps:8.0-jammy-chiseled-extra`

In the invariant case, then the nightly AOT image remains correct.

This change can go into servicing. If it breaks anyone, we have other problems.

The non-nightly images and 8.0.200 arrived at around the same time, hence the timing. This is fine to patch after-the-fact.

**Comment by richlander** [comment]
This is just something extra for our customers.

**Comment by baronfel** [comment]
I got this approved in Tactics today - it'll go with next months SDK
