### ISSUE TITLE
Determine inferencing for new Ubuntu `noble` images

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#557]
https://github.com/dotnet/dotnet-docker/pull/5241

It seems reasonable to default to these for .NET 9 Linux RIDs. The main question to me is: Is there a point at which we should ever default .NET 8 SDK containers to `noble`?

**Comment by richlander** [comment]
Having a default switch from `jammy` to `noble` seems fine to me as long as it is at an SDK feature band boundary. We do something similar for Alpine.

For example, we have an Alpine floating tag that gets updated ~ every 6 months to a new Alpine, some of which have breaking changes (most of which are hidden for most .NET apps).

- https://github.com/dotnet/dotnet-docker/discussions/5196
- https://github.com/dotnet/dotnet-docker/issues/4332

**Comment by baronfel** [comment]
Closing as we've done this work - the noble images will be used starting with the June servicing release for .NET 8.0.300+ SDKs.
