### ISSUE TITLE
Unable to use the ContainerRegistry as parameter on dotnet publish

### ISSUE THREAD

**Issue by Depechie** [dotnet/sdk-container-builds#565]
When using the DotNetCoreCLI@2 task in a Azure Devops pipeline, I can do a `dotnet publish` straight to my private Azure Container registry if I put the registry name as a property in the csproj file like: 
```
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ContainerRegistry>myawesomedummyname.azurecr.io</ContainerRegistry>
  </PropertyGroup>
```

But trying to move this to a command parameter like so:

```
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    projects: './src/ACAObservability.Web/ACAObservability.Web.csproj'
    arguments: >-
      -p:PublishProfile="DefaultContainer"
      -p:PublishSingleFile="true"
      -p:PublishTrimmed="false"
      --self-contained "true"
      --verbosity "quiet"
      --nologo
      -r "linux-amd64"
      -p:ContainerRepository="acaobservability.web"
      -p ContainerImageTags="\"$(dockerImageTag);latest\""
      -p:ContainerRegistry="myawesomedummyname.azurecr.io"'
```

I see in the build log, that the task obfuscates the registry name to ***
But it will also fail with the exception: `error CONTAINER2012: Could not recognize registry '***'`

**Comment by baronfel** [comment]
So you're saying that the AzDo task has mutated the registry URL?

**Comment by Depechie** [comment]
The build task logs the actual constructed publish command and it reads like so:

```
/usr/bin/dotnet publish /home/vsts/work/1/s/./src/ACAObservability.Web/ACAObservability.Web.csproj -p:PublishProfile=DefaultContainer -p:PublishSingleFile=true -p:PublishTrimmed=false --self-contained true --verbosity quiet --nologo -r linux-amd64 -p:ContainerRepository=acaobservability.web -p ContainerImageTags="187;latest" -p:ContainerRegistry=***'
```

Not sure 'who' does the obfuscation or mutation, but yeah that is what I notice indeed.

**Comment by chrisoverzero** [comment]
This may seem like a silly question, but could this be due to the stray single quote after the parameter?

```
-p:ContainerRegistry="myawesomedummyname.azurecr.io"'
```

It shows up in the build task logs, too:

```
-p:ContainerRegistry=***'
```

**Comment by baronfel** [comment]
That's an excellent idea @chrisoverzero.

One way we could find out for sure is with a binlog - one of the first lines in the binlog viewer is the complete MSBuild command line as seen by the engine.

**Comment by Depechie** [comment]
Totally not a silly question!!
Was a copy paste error :( the actual yaml file does not have that.

**Comment by Depechie** [comment]
Hmmm now that you mention it, the composed logs has indeed the '

Let me change the yaml again and retest.

I will get back with more info.

**Comment by Depechie** [comment]
Ok sorry for the inconvenience... I indeed had a rogue ' ( checked the GIT log ).
And without it, everything works perfectly!

**Comment by baronfel** [comment]
Glad to hear it @Depechie!
