### ISSUE TITLE
Document support for insecure registries

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#571]
Once https://github.com/dotnet/sdk/pull/39840 lands we will support writing to insecure registries following the existing container engine mechanisms ([insecure-registries](https://docs.docker.com/reference/cli/dockerd/#insecure-registries) in docker daemon.json config, podman [registries.conf configuration](https://podman-desktop.io/docs/containers/registries#setting-up-a-registry-with-an-insecure-certificate)).

We should document this support and point to the official resources for configuring these kinds of registries.

**Comment by tmds** [comment]
@baronfel when configuring a registry as insecure, both podman and docker allow the connection to be either unencrypted HTTP or HTTPS with an untrusted certificate.

The implementation added in https://github.com/dotnet/sdk/pull/39840 is only supporting the first.

**Comment by baronfel** [comment]
Thanks! Logged an issue to expand our support - are you noting the gap or did you try to use the new support and got blocked by this in your workflow?

**Comment by tmds** [comment]
> are you noting the gap or did you try to use the new support and got blocked by this in your workflow?

I know from using it with podman that it enables both scenarios.

I was looking whether the SDK already has some support for configuring insecure registries, and I noticed the difference in behavior implemented in the PR.

The registry I need it for is HTTP, so I'm not blocked. It would be easier if I can use an envvar. I may look into contributing [SDK_CONTAINER_INSECURE_REGISTRIES](https://github.com/dotnet/sdk-container-builds/issues/338#issuecomment-1792565724) to enable that.

**Comment by baronfel** [comment]
Effectively if we wanted to support HTTPS we'd have to override the cert validation callback to check the domain against the list of known-insecure domains before accepting the cert, right?

**Comment by tmds** [comment]
Yes, we'd override the callback to allow cert issues when the hostname is an insecure one.

We also don't know if the endpoint is http/https so we need to switch when needed.
