### ISSUE TITLE
Expose ContainerPort via API and in task

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/sdk-container-builds#59]
yeah - these ContainerPort items will eventually need to be mapped to the container config. this will make naieve `docker run` commands Just Work. Without it, users would need to add `--port EXTERNAL:INTERNAL` entries for each port manually at run-time.

_Originally posted by @baronfel in https://github.com/rainersigwald/containers/pull/54#discussion_r939062942_

**Comment by baronfel** [comment]
Completed in #93
