### ISSUE TITLE
providing a unified publish command

### ISSUE THREAD

**Issue by Varorbc** [dotnet/sdk-container-builds#602]
I've noticed that web projects and non-web projects use different commands for publish. 

I suggest providing a unified publish command that can be used for both web projects and non-web projects.

- for existing web project (the package is part of `Microsoft.NET.SDK.Web):

```shell
dotnet publish --os linux --arch x64 -c Release /p:PublishProfile=DefaultContainer
```

- for existing non-web project:

```shell
dotnet add package Microsoft.NET.Build.Containers
dotnet publish --os linux --arch x64 -c Release /t:PublishContainer
```

**Comment by baronfel** [comment]
The publishprofile command is deprecated, all projects can use the -t:PublishContainer form, and we've been switching doc and guidance over to that form for the past year or so.

**Comment by baronfel** [comment]
I've just done a pass through this repo and corrected the old usages.
