### ISSUE TITLE
Design and implement authentication to registries

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#70]
Currently we support pushing images to unauthenticated registries and the local Docker daemon. We need to be able to push to authenticated registries of all kinds.

There are two major standards for authenticating against registries that we should support: 
* HTTP Basic Auth 
* HTTP Bearer Token auth

Both of these credentials can be retrieved from a file on the users system, whose location and format is described in detail [here](https://www.mankier.com/5/containers-auth.json). The file contains three relevant structures: 
* an `auths` mapping of domain name (optionally namespace/user/image sections as well) to credentials
  *  these credentials are `username:password` values in base64 encoding
* a `credHelpers` mapping of domain name (optionally namespace/user/image sections as well) to the name of an executable to invoke 
  * these executables are invoked with the `get` command, and then the target url (as defined in the key of the mapping) is written to stdin. stdout will either contain an error message or the [json representation of the credential struct](https://github.com/docker/docker-credential-helpers/blob/e595cd69465c6b0f7af2d49582b82fdeddecbf75/credentials/credentials.go#L14-L18)
* a `credStore` value describing the application to invoke
  * these applications follow the same protocol as the credHelpers above, but use the system keychain generally and apply to all hosts

In all cases, if the username of the credential is `<token>`, the secret portion of the credential is to be treated as a Bearer token instead of the overall transaction being HTTP Basic Auth.
 
The above will allow us to seamlessly integrate with existing container applications and flows. In addition, we should also support four new MSBuild properties to allow for arbitrary authentication, though we should document these as a) being insecure, and b) less desired than the more 'standard' auth flows described above. The proposed properties are

* BaseRegistryUsername
* BaseRegistryPassword
* BaseRegistryToken
* TargetRegistryUsername
* TargetRegistryPassword
* TargetRegistryToken

For each triplet of properties (Base vs Target), the Username and Password properties are mutually exclusive to the Token property. This makes it very clear whether Basic auth or Bearer auth will be used.

We should provide a well-known target that third parties can use as a place to perform authentication. This is commonly required by cloud providers, for example, who might use a scheme of long-lived refresh tokens and short-lived access tokens to create a temporary authorization to push to a specific registry. The name of this target (and the property to add dependencies to in order to hook into it) should be documented and remain stable.

We need to have very explicit handling around authentication failures for registry calls - users need a specific error code they can look up and have pre-written docs for.

**Comment by baronfel** [comment]
@mthalman mentioned [here](https://github.com/microsoft/dotnet-blog/pull/884#discussion_r949543220) that he has a library that implemented the credential store logic already: https://github.com/mthalman/docker-creds-provider

**Comment by baronfel** [comment]
Going to chat with the SourceBuild folks about the logistics of using @mthalman's library to make sure there are no blockers.

**Comment by normj** [comment]
I'm trying to imagine how we could fit the login process for AWS's registry Elastic Container Registry (ECR). ECR uses short term credentials for the login so we would need a way to hook into the login process to generate the temporary credentials. Is there any plans for this feature to register a hook, maybe a build time NuGet package or something?

**Comment by baronfel** [comment]
We could definitely expose a known MSBuild target (something like "AuthenticateToRegistry") that exposes a property for its `DependsOnTargets` attribute that would allow folks to add in targets to call that would set the well-known properties (or modify the docker config, etc) in a way that we could just pick them up. Is that what you're thinking?

```xml
<Target Name="AuthenticateToRegistry" DependsOnTargets="$(AuthenticateToRegistryDependsOn)" />

<!-- AWS targets could expose something like -->
<Target Name="LogintoECR">
  <ECRLogin Registry="$(ContainerRegistry)">
      <Output TaskParameter="ECRToken" PropertyName="$(TargetRegistryToken)" />
  </ECRLogin>
</Target>
```

**Comment by baronfel** [comment]
Alternatively, if the user already has a token in the docker config (from something like `aws ecr get-login-password --region region | docker login --username AWS --password-stdin`) that that should just work if we implement the docker-auth conventions.

**Comment by rainersigwald** [comment]
I would definitely prefer to lean on OS secret store/Docker credential stuff and keep secrets out of MSBuild logs as much as possible. It should be possible to create a NuGet package that has a `BeforeTargets="PublishContainer"` that does the equivalent of the pipe-to-docker-login snippet above. Does that strategy seem reasonable @normj?

**Comment by christiannagel** [comment]
It can be of interest how the [dotnet tye](https://github.com/dotnet/tye) team did the authentication to registries

**Comment by baronfel** [comment]
@christiannagel from what I can tell, tye worked by orchestrating CLI commands to the underlying container engine (Docker CLI or Podman CLI), and so it also used the configuration file approach discussed here.

**Comment by baronfel** [comment]
Currently #182 will use the docker credential subsystems for authentication, including any configured credential helpers.  For the VS integration, If we detect that the required credential helpers are not available (they do not exist in the PATH), VS with authenticate and provide credentials through the TaskHost. We should expose the ability to check for the existence of credential managers as a target and allow VS to invoke that target explicitly.

We need to verify that podman/nerdctl work with docker credential managers.

**Comment by baronfel** [comment]
As of the 0.2.7 release of this package we support private registry authentication! See [the in-repo docs](https://github.com/dotnet/sdk-container-builds/blob/main/docs/RegistryAuthentication.md) for details, but in general if you can authenticate via `docker login` to your registry (or use a credential helper to manage that authentication), then we will respect that configuration.
