### ISSUE TITLE
Implement conventional labels on top of existing label infrastructure

### ISSUE THREAD

**Issue by baronfel** [dotnet/sdk-container-builds#96]
## Labels

There are some [well-known labels](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys) that we should consider setting by default:

| Annotation Key | Derived from |
| - | - |
| org.opencontainers.image.created |  `$([System.DateTime]::UtcNow.ToString("o"))` |
| org.opencontainers.image.description | `$(Description)` | 
| org.opencontainers.image.authors | `$(Authors)` | 
| org.opencontainers.image.url | `$(PackageProjectUrl)` if present. |
| org.opencontainers.image.documentation | Since `$(PackageLicenseUrl)` is deprecated, we may just have to default to `$(RepositoryUrl)`. Users should be able to override this easily though. |
| org.opencontainers.image.version | `$(Version)` if present. Note that there's not really a consistent place to hook into where we can be assured of a version being set, so we'll want to be sometime directly before `Build`, but as late as possible otherwise. |
| org.opencontainers.image.vendor | There's no `$(PackageOwners)` or `$(Owners)` to bootstrap off of, but maybe we should make one? |
| org.opencontainers.image.licenses | `$(PackageLicenseExpression)`  |
| org.opencontainers.image.title | `$(Title)` |
| org.opencontainers.image.base.digest | The resolved digest of `$(ContainerBaseImage)`. We don't calculate this yet so can't do it. |
| org.opencontainers.image.base.name | `$(ContainerBaseImage)` | 
| org.opencontainers.image.source |`$(PrivateRepositoryUrl)` if present and `$(PublishRepositoryUrl)` is true. |
| org.opencontainers.image.revision | `$(RepositoryCommit)` if present and `$(PublishRepositoryUrl)` is true. |

**Comment by rklec** [comment]
FYI https://learn.microsoft.com/en-us/dotnet/core/containers/publish-configuration#default-container-labels does not seem to document all these new ones, currently.
